# -*- coding: utf-8 -*-
"""
InfraredCityGIS
                                 A QGIS plugin
 This is a plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-10-13
        copyright            : (C) 2025 by infrared.city
        email                : connectors@infrared.city
        git sha              : $Format:%H$
"""

"""
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


from .utils.deps_bootstrap import ensure_deps as _ensure_deps  # noqa: E402

_ensure_deps("infrared_city_gis")


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load InfraredCityGIS class from file InfraredCityGIS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .infrared_city_gis import InfraredCityGIS
    return InfraredCityGIS(iface)
