# -*- coding: utf-8 -*-
"""
/***************************************************************************
 InfraredCityDialog
                                 A QGIS plugin
 This is a plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-13
        git sha              : $Format:%H$
        copyright            : (C) 2025 by infrared.city
        email                : connectors@infrared.city
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtWidgets import QMessageBox
from .infrared_logger import logger
from .visualization.display import display_geojson
from .services.fetch import fetch_geometry_from_osm, fetch_weather_file_names
from .exceptions import InfraredAPIError
import json
from qgis.core import QgsApplication
# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'infrared_city_fetch_weather_file_names_dialog.ui'))


class InfraredCityFetchWeatherFileNamesDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(InfraredCityFetchWeatherFileNamesDialog, self).__init__(parent)

        self.setupUi(self)
        logger.info("Dialog loaded")

        self.button_box.accepted.connect(self.accept)
        self.button_box.rejected.connect(self.reject)
        self.api_key = None
        
        plugin_data_dir = os.path.join(QgsApplication.qgisSettingsDirPath(), "infrared_city_gis", "settings")
        user_file = os.path.join(plugin_data_dir, "user.json")

        if os.path.exists(user_file):
            try:
                with open(user_file, "r", encoding="utf-8") as f:
                    data = json.load(f)
                    api_key = data.get("api-key", "")
                    self.api_key_input.setText(api_key)
                    self.api_key = api_key
                    logger.info(f"Loaded API key from user.json: {api_key}")
            except Exception as e:
                logger.warning(f"Could not read API key: {e}")
                QMessageBox.warning(self, "Invalid API Key", "Invalid API key. Please check the input values.")



    def accept(self):
        """Run fetch when OK is pressed."""
        longitude = self.longitude_input.text().strip()
        latitude = self.latitude_input.text().strip()
        radius = self.radius_input.text().strip()
        
        # --- Validation ---
        if not longitude or not latitude or not radius:
            logger.warning("Missing input")
            QMessageBox.warning(self, "Missing Input", "Please fill in all fields!")
            return

        try:
            lon = float(longitude)
            lat = float(latitude)
            radius = float(radius)
        except ValueError:
            logger.error("Invalid input")
            QMessageBox.warning(self, "Invalid Input", "Coordinates and bbox must be numbers.")
            return
        
        plugin_data_dir = os.path.join(QgsApplication.qgisSettingsDirPath(), "infrared_city_gis", "settings")
        os.makedirs(plugin_data_dir, exist_ok=True)
        user_file = os.path.join(plugin_data_dir, "user.json")

        self.api_key = self.api_key_input.text().strip()
        if self.api_key:
            try:
                with open(user_file, "w", encoding="utf-8") as f:
                    json.dump({"api-key": self.api_key}, f, indent=2)
                    logger.info("API key saved successfully.")
            except Exception as e:
                logger.error(f"Failed to save API key: {e}")
        else:
            logger.warning("API key is empty. Please fill in the API key.")
            QMessageBox.warning(self, "Missing API Key", "Please fill in the API key.")
            return

        # --- Fetch ---
        try:
            locations = fetch_weather_file_names(lon, lat, radius, self.api_key)

            #save_locations_to_file(locations)

        except InfraredAPIError as e:
            logger.error(f"API error fetching weather file names: {e}", exc_info=True)
            QMessageBox.critical(self, e.title, e.detail)
            return
        except Exception as e:
            logger.error(f"Failed to fetch weather file names: {e}", exc_info=True)
            QMessageBox.critical(self, "Error", f"Failed to fetch weather file names.\n\n{e}")
            return

        super().accept()