# -*- coding: utf-8 -*-
"""
/***************************************************************************
 InfraredCityDialog
                                 A QGIS plugin
 This is a plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-13
        git sha              : $Format:%H$
        copyright            : (C) 2025 by infrared.city
        email                : connectors@infrared.city
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtWidgets, uic
from qgis.PyQt.QtWidgets import QMessageBox

from .infrared_logger import logger
from .services.fetch import fetch_geometry_from_osm
from .visualization.display import display_geojson

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'infrared_city_fetch_geometry_dialog.ui'))


class InfraredCityFetchGeometryDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(InfraredCityFetchGeometryDialog, self).__init__(parent)

        self.setupUi(self)
        logger.info("Dialog loaded")

        self.button_box.accepted.connect(self.accept)
        self.button_box.rejected.connect(self.reject)

    def accept(self):
        """Run fetch when OK is pressed."""
        longitude = self.longitude_input.text().strip()
        latitude = self.latitude_input.text().strip()
        bbox_val = float(self.bbox_input.value())

        # --- Validation ---
        if not longitude or not latitude:
            logger.warning("Missing input")
            QMessageBox.warning(self, "Missing Input", "Please fill in all fields!")
            return

        try:
            lon = float(longitude)
            lat = float(latitude)
        except ValueError:
            logger.error("Invalid input")
            QMessageBox.warning(self, "Invalid Input", "Coordinates and bbox must be numbers.")
            return

        # --- Fetch ---
        try:
            geojson_path, dotbim_path, bbox = fetch_geometry_from_osm(lon, lat, bbox_val)
            # TODO: apply ground material fetching

            if not geojson_path or not dotbim_path or not bbox:
                logger.error("Failed to fetch geometry")
                QMessageBox.warning(self, "Invalid Input", "Invalid coordinates, please use different lon,lat coords.")
                return

            self.geojson_path = geojson_path
            self.dotbim_path = dotbim_path
            self.bbox = bbox

            display_geojson(geojson_path)
            # TODO: adjust ground materil displya
            # display_ground_materials(ground_materials)

        except Exception as e:
            logger.error(f"Failed to fetch geometry: {e}")
            return

        super().accept()
