# -*- coding: utf-8 -*-
"""
/***************************************************************************
 InfraredCityDialog
                                 A QGIS plugin
 This is a plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-13
        git sha              : $Format:%H$
        copyright            : (C) 2025 by infrared.city
        email                : daniel.lepold@infrared.city
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import json
from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtWidgets import QMessageBox
from .infrared_logger import logger
from .visualization.display import display_geojson
from .services.fetch import fetch_geometry_from_osm
from .client import process_run_analysis, process_ogc, get_windspeed_payload
from .infrared_logger import logger
from .visualization.display import add_geojson_then_raster, display_route_and_points
from .services.geometry import get_bbox

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'infrared_city_run_multiple_dialog.ui'))


class InfraredCityRunMultipleDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(InfraredCityRunMultipleDialog, self).__init__(parent)
        self.setupUi(self)

        logger.info("Dialog loaded")

        self.button_box.accepted.connect(self.accept)
        self.button_box.rejected.connect(self.reject)

    def accept(self):
        """Run fetch when OK is pressed."""

        api_key = "Rs1MoXnOUn4PPPQ3LT7JZ8LN5J5SvV615rik1JgI"


        coordinates = [[135.16825585757928,34.67417810179636],
            [135.1654625722112,34.674533695535075],
            [135.16514299983947,34.67222602971341],
            [135.16234978236636,34.67244085210026],
            [135.1620303131685,34.67013318548488],
            [135.1592371659463,34.67034799560734]]

        plugin_dir = os.path.dirname(os.path.abspath(__file__))

        # Build path to route.json
        route_path = os.path.join(plugin_dir, "route.json")


        # Load coordinates from your JSON file
        with open(route_path, 'r') as f:
            route = json.load(f)




        tile_id = 0
        for coordinate in coordinates:
            longitude = coordinate[0]
            latitude = coordinate[1]
            bbox = 512
        # --- Fetch ---
            try:
                geojson_path, dotbim_path, bbox = fetch_geometry_from_osm(longitude, latitude, bbox,retries=3,delay=3,tile_id=tile_id)

                bbox_cropped = get_bbox(longitude, latitude, 256)
                logger.info("Simulation started")
                payload = get_windspeed_payload(dotbim_path, 45, 15,bbox_cropped)
                geotiff_path = process_run_analysis(payload,dotbim_path,bbox_cropped,"EPSG:4326", api_key,True)
                logger.info("Simulation finished")
                    
                add_geojson_then_raster(geojson_path, geotiff_path, "wind-speed",None)
                display_route_and_points(route, coordinates)

                logger.info("Geotiff visualized")
                tile_id += 1
            except Exception as e:
                logger.error("Simulation failed")
                logger.error(f"Error happened: {e}")
                raise        
    
        super().accept()