# -*- coding: utf-8 -*-
"""
/***************************************************************************
 InfraredCityDialog
                                 A QGIS plugin
 This is a plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-13
        git sha              : $Format:%H$
        copyright            : (C) 2025 by infrared.city
        email                : daniel.lepold@infrared.city
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtWidgets import QMessageBox
from .client import (
    get_windspeed_payload_ogc, get_pwc_payload_ogc,
    get_utci_payload_ogc, get_tcs_payload_ogc,
    process_ogc
)
from .infrared_logger import logger
import json
from qgis.core import QgsApplication
from .models.analysis import AnalysisType, PedestrianWindComfortType, ThermalComfortStatisticsType
from .models.timeframes_parser import SeasonalTimeFrameConfig, DailyTimeFrameConfig,DailyTimeFrameConfigUTCI, validate_weather_filename, MonthConfig
from .models.weather_files import WeatherFile
from .services.geometry import collect_tile_centers_from_selection, collect_geometry_data_by_tile, crop_matrix, generate_geotiff
import rasterio
from .visualization.display import add_geojson_then_raster
from qgis.PyQt.QtWidgets import QProgressBar
from qgis.utils import iface
from qgis.core import Qgis

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'infrared_city_run_simulation_dialog.ui'))


class InfraredCityRunMultipleSimulationDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)

        self.dotbim_path = None
        self.geojson_path = None
        self.geotiff_path = None
        self.colors = None
        self.analysis_type_dropdown.clear()
        for t in AnalysisType:
            self.analysis_type_dropdown.addItem(str(t), t)
        self.analysis_type_dropdown.currentTextChanged.connect(self.on_analysis_changed)
        self.analysis_type = None
        self.api_key = None
        
        self.button_box.accepted.connect(self.accept)
        self.button_box.rejected.connect(self.reject)

        # Állítsuk be az alapértelmezett oldalt a stack-ben
        if self.analysis_type_dropdown.count() > 0:
            self.analysis_type_dropdown.setCurrentIndex(0)
            self.on_analysis_changed(self.analysis_type_dropdown.currentText())

        
        plugin_data_dir = os.path.join(QgsApplication.qgisSettingsDirPath(), "infrared_city_gis", "settings")
        user_file = os.path.join(plugin_data_dir, "user.json")

        if os.path.exists(user_file):
            try:
                with open(user_file, "r", encoding="utf-8") as f:
                    data = json.load(f)
                    api_key = data.get("api-key", "")
                    self.api_key_input.setText(api_key)
                    self.api_key = api_key
                    logger.info(f"Loaded API key from user.json: {api_key}")
            except Exception as e:
                logger.warning(f"Could not read API key: {e}")
                QMessageBox.warning(self, "Invalid API Key", "Invalid API key. Please check the input values.")

        logger.info("Dialog loaded")

    def on_analysis_changed(self, text):
        current = self.analysis_type_dropdown.currentData()
        # Switch stacked pages instead of toggling visibility
        try:
            if current == AnalysisType.WIND_SPEED:
                self.content_stack.setCurrentIndex(0)
            elif current == AnalysisType.PEDESTRIAN_WIND_COMFORT:
                self.content_stack.setCurrentIndex(1)
            elif current == AnalysisType.THERMAL_COMFORT_INDEX:
                self.content_stack.setCurrentIndex(2)
            elif current == AnalysisType.THERMAL_COMFORT_STATISTICS:
                self.content_stack.setCurrentIndex(3)
        except AttributeError:
            # Fallback for older UI without stacked widget
            try:
                self.group_wind_speed.setVisible(current == AnalysisType.WIND_SPEED)
                self.group_pedestrian_wind_comfort.setVisible(current == AnalysisType.PEDESTRIAN_WIND_COMFORT)
                self.group_thermal_comfort.setVisible(current == AnalysisType.THERMAL_COMFORT_INDEX)
                self.group_thermal_comfort_statistics.setVisible(current == AnalysisType.THERMAL_COMFORT_STATISTICS)
            except AttributeError as e:
                logger.error("Failed to update group visibility: %s", str(e), exc_info=True)

        if current == AnalysisType.PEDESTRIAN_WIND_COMFORT:
            try:
                self.weather_file_input_pwc.setEditable(True)
                self.weather_file_input_pwc.clear()

                for w in WeatherFile:
                    self.weather_file_input_pwc.addItem(w.value, w)

                self.pwc_type_dropdown.clear()
                for s in PedestrianWindComfortType:
                    self.pwc_type_dropdown.addItem(str(s), s)

                self.season_dropdown_pwc.clear()
                for season in SeasonalTimeFrameConfig:
                    self.season_dropdown_pwc.addItem(season.value, season)

                self.hours_dropdown_pwc.clear()
                for hours in DailyTimeFrameConfig:
                    self.hours_dropdown_pwc.addItem(hours.value, hours)
            except Exception as e:
                logger.error("Failed to populate PWC dialog elements: %s", str(e), exc_info=True)
        
        if current == AnalysisType.THERMAL_COMFORT_INDEX:
            try:
                self.weather_file_input_tci.setEditable(True)
                self.weather_file_input_tci.clear()

                for w in WeatherFile:
                    self.weather_file_input_tci.addItem(w.value, w)

                self.legend_min_input_tci.setEnabled(False)
                self.legend_max_input_tci.setEnabled(False)

                self.legend_min_enable_tci.toggled.connect(
                    self.legend_min_input_tci.setEnabled
                )
                self.legend_max_enable_tci.toggled.connect(
                    self.legend_max_input_tci.setEnabled
                )

                self.month_dropdown_tci.clear()
                for month in MonthConfig:
                    self.month_dropdown_tci.addItem(month.value, month)

                self.hours_dropdown_tci.clear()
                for hours in DailyTimeFrameConfigUTCI:
                    self.hours_dropdown_tci.addItem(hours.value, hours)
            except AttributeError as e:
                logger.error("Failed to populate TCI dialog elements: %s", str(e), exc_info=True)

        if current == AnalysisType.THERMAL_COMFORT_STATISTICS:
            try:
                self.weather_file_input_tcs.setEditable(True)
                self.weather_file_input_tcs.clear()

                for w in WeatherFile:
                    self.weather_file_input_tcs.addItem(w.value, w)

                self.season_dropdown_tcs.clear()
                for season in SeasonalTimeFrameConfig:
                    self.season_dropdown_tcs.addItem(season.value, season)

                self.hours_dropdown_tcs.clear()
                for hours in DailyTimeFrameConfig:
                    self.hours_dropdown_tcs.addItem(hours.value, hours)

                self.tcs_type_dropdown.clear()
                for tcs_type in ThermalComfortStatisticsType:
                    self.tcs_type_dropdown.addItem(tcs_type.value, tcs_type)
            except Exception as e:
                logger.error("Failed to populate TCS dialog elements: %s", str(e), exc_info=True)

    
    def accept(self):
        logger.info("\n ✨ ✨ ✨ ✨ ✨ ✨ ✨ MULTIPLE SIMULATION RUN START ✨ ✨ ✨ ✨ ✨ ✨ ✨ ")
        logger.info(f"Accept called. Sender: {self.sender()}")
        tile_centers = collect_tile_centers_from_selection()

        self.analysis_type = self.analysis_type_dropdown.currentData()
        self.sub_analysis_type = None
        selected_legend_min = None
        selected_legend_max = None


        plugin_data_dir = os.path.join(QgsApplication.qgisSettingsDirPath(), "infrared_city_gis", "settings")
        os.makedirs(plugin_data_dir, exist_ok=True)
        user_file = os.path.join(plugin_data_dir, "user.json")

        self.api_key = self.api_key_input.text().strip()
        if self.api_key:
            try:
                with open(user_file, "w", encoding="utf-8") as f:
                    json.dump({"api-key": self.api_key}, f, indent=2)
                    logger.info("API key saved successfully.")
            except Exception as e:
                logger.error(f"Failed to save API key: {e}")
        else:
            logger.warning("API key is empty. Please fill in the API key.")
            QMessageBox.warning(self, "Missing API Key", "Please fill in the API key.")
            return

        # ---------  Preparing payloads -----------------
        if self.analysis_type == AnalysisType.WIND_SPEED:
            # Validation
            wind_speed = self.wind_speed_input.value()
            wind_direction = self.wind_direction_input.value()
            
            if  (wind_speed <= 0 or wind_direction < 0 or wind_direction > 360):
                logger.warning("Invalid parameters. Please check the input values.")
                QMessageBox.warning(self, "Invalid Parameters", "Wind speed must be >0 and direction between 0-360°.")
                return

            payload = get_windspeed_payload_ogc(None, None, None, wind_direction, wind_speed)
            logger.info(f"Payload created: {payload}")
            
     
        elif self.analysis_type == AnalysisType.PEDESTRIAN_WIND_COMFORT:
            # Validation
            try:
                pwc_type = self.pwc_type_dropdown.currentData()
                self.sub_analysis_type = pwc_type
                selected_season = self.season_dropdown_pwc.currentData()   
                selected_hours = self.hours_dropdown_pwc.currentData()
                weather_file = self.weather_file_input_pwc.currentText().strip()
                logger.info(f"Weather file: {weather_file}")

                if not validate_weather_filename(weather_file):
                    logger.warning("Invalid weather file name. Please check the input values.")
                    QMessageBox.warning(
                        self,
                        "Invalid Weather File",
                        "Invalid weather file name. Please check the input values."
                    )
                    return

            except AttributeError:
                logger.warning("Missing input")
                QMessageBox.warning(self, "Missing Input", "Please fill in all fields!")
                return

            payload = get_pwc_payload_ogc(None, None, None, pwc_type.value, selected_season.value, selected_hours.value, weather_file)
            logger.info(f"Payload created: {payload}")

        
        elif self.analysis_type == AnalysisType.THERMAL_COMFORT_INDEX:
            # Validation
            try:
                selected_month = self.month_dropdown_tci.currentData()      
                selected_hours = self.hours_dropdown_tci.currentData()
                if self.legend_min_enable_tci.isChecked():
                    selected_legend_min = self.legend_min_input_tci.value()
                else:
                    selected_legend_min = None
                if self.legend_max_enable_tci.isChecked():
                    selected_legend_max = self.legend_max_input_tci.value()
                else:
                    selected_legend_max = None

                weather_file = self.weather_file_input_tci.currentText().strip()
                logger.info(f"Weather file: {weather_file}")

                if not validate_weather_filename(weather_file):
                    logger.warning("Invalid weather file name. Please check the input values.")
                    QMessageBox.warning(
                        self,
                        "Invalid Weather File",
                        "Invalid weather file name. Please check the input values."
                    )
                    return

            except AttributeError:
                logger.warning(f"Missing input, Selected season and hours are required.")
                QMessageBox.warning(self, "Missing Input", "Selected season and hours are required.")
                selected_legend_min = None
                selected_legend_max = None
                return
            
            payload = get_utci_payload_ogc(None, None, None, selected_month.number, selected_hours.value, weather_file)
            logger.info(f"Payload created: {payload}")

        elif self.analysis_type == AnalysisType.THERMAL_COMFORT_STATISTICS:
            # Validation
            try:
                selected_season = self.season_dropdown_tcs.currentData()
                selected_hours = self.hours_dropdown_tcs.currentData()
                selected_tcs_type = self.tcs_type_dropdown.currentData()

                weather_file = self.weather_file_input_tcs.currentText().strip()
                logger.info(f"Weather file: {weather_file}")

                if not validate_weather_filename(weather_file):
                    logger.warning("Invalid weather file name. Please check the input values.")
                    QMessageBox.warning(
                        self,
                        "Invalid Weather File",
                        "Invalid weather file name. Please check the input values."
                    )   
            except AttributeError:
                logger.warning("Missing input. TCS type is required.")
                QMessageBox.warning(self, "Missing Input", "TCS type is required.")
                return

            payload = get_tcs_payload_ogc(None, None, None, selected_season.value, selected_hours.value, weather_file, selected_tcs_type.value)
            logger.info(f"Payload created: {payload}")

        for idx, (center_x, center_y) in enumerate(tile_centers):
            logger.info("Processing tile center %d: %s, %s", idx, center_x, center_y)
            res = collect_geometry_data_by_tile(center_x, center_y, idx)
            if not res:
                continue

            geojson_path, dotbim_path, bbox_512, crs_authid, bbox_256 = res
            
            # Read the existing dotbim content and dump it again
            with open(dotbim_path, "r", encoding="utf-8") as f:
                dotbim_data = json.load(f)
            

            # Crop 512x512 GeoTIFF to 256x256 around the tile center and display
            try:
                logger.info("Starting wind speed OGC simulation for tile %d", idx)
                
                payload["inputs"]["geometries"] = dotbim_data
                payload["inputs"]["bbox"] = bbox_512
                payload["inputs"]["crs"] = crs_authid

                
                geotiff_path = process_ogc(payload, dotbim_path, self.analysis_type.value, self.api_key)
                logger.info("Simulation finished for tile %d", idx)

                # Crop 512x512 GeoTIFF to 256x256 around the tile center and display
                try:
                    with rasterio.open(geotiff_path) as src:
                        matrix = src.read(1)

                    cropped_matrix = crop_matrix(matrix, core_size=256)
                    sub_bbox = bbox_256

                    base_name = os.path.splitext(os.path.basename(geotiff_path))[0]
                    plugin_data_dir = os.path.dirname(geotiff_path)
                    cropped_geotiff_path = os.path.join(plugin_data_dir, f"{base_name}_crop.tif")

                    generate_geotiff(
                        cropped_matrix,
                        sub_bbox,
                        crs_authid,
                        cropped_geotiff_path,
                        simulation_type=self.analysis_type.value,
                    )

                    add_geojson_then_raster(
                        geojson_path=geojson_path,
                        geotiff_path=cropped_geotiff_path,
                        analysis_type=self.analysis_type.value,
                        sub_analysis_type=self.sub_analysis_type.value if self.sub_analysis_type is not None else None,
                        min_legend_value=selected_legend_min,
                        max_legend_value=selected_legend_max
                    )
                    logger.info("Cropped Geotiff visualized for tile %d", idx)

                    iface.messageBar().pushMessage(
                        "InfraredCity",
                        f"Tile {idx+1}/{len(tile_centers)} processed successfully, saved to {cropped_geotiff_path}",
                        level=Qgis.Success,
                        duration=3
                    )
                except Exception as e_crop:
                    logger.error("Failed to crop/display GeoTIFF for tile %d: %s", idx, e_crop)
            except Exception as e:
                logger.error("Simulation failed for tile %d: %s", idx, e)

                iface.messageBar().pushMessage(
                        "InfraredCity",
                        f"Error processing tile {idx+1}/{len(tile_centers)}: {str(e)}",
                        level=Qgis.Warning,
                        duration=5
                    )
                    

            logger.info(f"Processed tile: {idx+1}/{len(tile_centers)}.")
            
        super().accept()