# -*- coding: utf-8 -*-
"""
/***************************************************************************
 InfraredCityDialog
                                 A QGIS plugin
 This is a plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-13
        git sha              : $Format:%H$
        copyright            : (C) 2025 by infrared.city
        email                : daniel.lepold@infrared.city
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import json
import rasterio
from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtWidgets import QMessageBox
from qgis.core import (
    QgsProject,
    QgsVectorLayer,
    QgsFields,
    QgsField,
    QgsFeature,
    QgsGeometry,
    QgsPointXY,
    QgsRectangle,
    QgsCoordinateTransform,
    QgsCoordinateReferenceSystem,
    QgsApplication,
    QgsUnitTypes,
)
from qgis.PyQt.QtCore import QVariant
from .infrared_logger import logger
from .visualization.display import display_geojson
from .services.fetch import fetch_geometry_from_osm
from .client import process_run_analysis, process_ogc, get_windspeed_payload, get_windspeed_payload_ogc
from .infrared_logger import logger
from .visualization.display import add_geojson_then_raster, display_route_and_points
from .services.geometry import get_bbox, crop_matrix, generate_geotiff
from .services.geojson2dotbim import process_geojson_file
from .models.analysis import AnalysisType
from qgis.utils import iface
from datetime import datetime
import math


# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'infrared_city_run_multiple_dialog.ui'))


class InfraredCityRunMultipleDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(InfraredCityRunMultipleDialog, self).__init__(parent)
        self.setupUi(self)

        logger.info("Dialog loaded")

        self.button_box.accepted.connect(self.accept)
        self.button_box.rejected.connect(self.reject)

        self.date_now = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')

    def _get_selected_bbox(self):
        """
        Returns the bbox of the selected features.
        """
        layer = iface.activeLayer()
        if layer is None:
            raise RuntimeError("No active layer.")

        selected = layer.selectedFeatures()
        if not selected:
            raise RuntimeError("No selected features.")

        # Első feature bbox-a
        geom = selected[0].geometry()
        if geom is None or geom.isEmpty():
            raise RuntimeError("The first selected geometry is empty.")
        bbox = geom.boundingBox()

        for feat in selected[1:]:
            g = feat.geometry()
            if g is None or g.isEmpty():
                continue
            bbox.combineExtentWith(g.boundingBox())

        west  = bbox.xMinimum()
        south = bbox.yMinimum()
        east  = bbox.xMaximum()
        north = bbox.yMaximum()

        return west, south, east, north

    def _generate_tile_centers(self, west, south, east, north, tile_size=256):

        width = east - west
        height = north - south

        if width <= 0 or height <= 0:
            logger.error("Invalid bbox.")
            raise ValueError("Invalid bbox.")

        nx = math.ceil(width / tile_size)
        ny = math.ceil(height / tile_size)

        centers = []

        for j in range(ny):
            cy = south + (j + 0.5) * tile_size
            for i in range(nx):
                cx = west + (i + 0.5) * tile_size
                centers.append((cx, cy))

        return centers

    def _display_tile_centers(self, tile_centers):
        """Create and display a temporary point layer from the tile centers."""
        layer = iface.activeLayer()
        if layer is None:
            raise RuntimeError("No active layer for tile center display.")

        crs_authid = layer.crs().authid()

        vl = QgsVectorLayer(f"Point?crs={crs_authid}", "InfraredCity tile centers", "memory")
        fields = QgsFields()
        fields.append(QgsField("id", QVariant.Int))
        vl.dataProvider().addAttributes(fields)
        vl.updateFields()

        features = []
        for idx, (x, y) in enumerate(tile_centers):
            feat = QgsFeature()
            feat.setFields(fields)
            feat.setAttribute("id", idx)
            feat.setGeometry(QgsGeometry.fromPointXY(QgsPointXY(x, y)))
            features.append(feat)

        vl.dataProvider().addFeatures(features)
        vl.updateExtents()

        QgsProject.instance().addMapLayer(vl)

    def _process_tile_center(self, center_x, center_y, idx):
        wgs84 = QgsCoordinateReferenceSystem("EPSG:4326")

        layer = iface.activeLayer()
        if layer is None or not isinstance(layer, QgsVectorLayer):
            for lyr in QgsProject.instance().mapLayers().values():
                if isinstance(lyr, QgsVectorLayer):
                    layer = lyr
                    break

        if layer is None or not isinstance(layer, QgsVectorLayer):
            logger.error("No valid vector layer found.")
            return None

        layer_crs = layer.crs()

        try:
            transform_to_wgs84 = QgsCoordinateTransform(layer_crs, wgs84, QgsProject.instance())
            pt_wgs84 = transform_to_wgs84.transform(QgsPointXY(center_x, center_y))
        except Exception as e:
            logger.error("Transform tile center to WGS84 failed: %s", e)
            return None

        center_lon, center_lat = pt_wgs84.x(), pt_wgs84.y()
        logger.info("Tile center (WGS84): %.6f, %.6f", center_lon, center_lat)

        try:
            xmin, ymin, xmax, ymax = get_bbox(center_lon, center_lat, 512)
            bbox_rect_wgs84 = QgsRectangle(xmin, ymin, xmax, ymax)
        except Exception as e:
            logger.error("get_bbox failed: %s", e)
            return None

        if layer_crs.authid() != "EPSG:4326":
            transform_bbox = QgsCoordinateTransform(wgs84, layer_crs, QgsProject.instance())
            bbox_rect_layer = transform_bbox.transformBoundingBox(bbox_rect_wgs84)
        else:
            bbox_rect_layer = bbox_rect_wgs84

        try:
            layer.removeSelection()
            layer.selectByRect(bbox_rect_layer, QgsVectorLayer.SetSelection)
            count = layer.selectedFeatureCount()
            logger.info("Tile %d: selected %d features.", idx, count)
        except Exception as e:
            logger.error("Selection failed for tile %d: %s", idx, e)
            return None

        selected_features = layer.selectedFeatures()
        if not selected_features:
            logger.info("Tile %d: no features selected, skipping.", idx)
            return None
        
        logger.info("Tile %d: processing %d selected features.", idx, len(selected_features))
        
        geojson_dict = {
            "type": "FeatureCollection",
            "features": []
        }

        fields = [field.name() for field in layer.fields()]

        for feat in selected_features:
            geom = feat.geometry()
            geom_wgs84 = QgsGeometry(geom)
            if layer_crs.authid() != "EPSG:4326":
                transform_to_wgs84_back = QgsCoordinateTransform(layer_crs, wgs84, QgsProject.instance())
                geom_wgs84.transform(transform_to_wgs84_back)

            attr_values = feat.attributes()
            properties_dict = {fields[i]: attr_values[i] for i in range(len(fields))}

            geom_bbox = geom.boundingBox()
            height = geom_bbox.height()

            if layer_crs.mapUnits() == QgsUnitTypes.DistanceDegrees:
                height *= 111_000

            properties_dict["height"] = round(height, 2)

            geojson_dict["features"].append({
                "type": "Feature",
                "geometry": json.loads(geom_wgs84.asJson()),
                "properties": properties_dict
            })

        plugin_data_dir = os.path.join(QgsApplication.qgisSettingsDirPath(), "infrared_city_gis", "data")
        os.makedirs(plugin_data_dir, exist_ok=True)
        geojson_path = os.path.join(plugin_data_dir, f"infrared_city_buildings_{self.date_now}_tile_{idx}.geojson")

        with open(geojson_path, "w", encoding="utf-8") as f:
            json.dump(geojson_dict, f, ensure_ascii=False, indent=2)

        dotbim_data = process_geojson_file(geojson_dict, center_lon, center_lat, "EPSG:4326")
        dotbim_path = os.path.join(plugin_data_dir, f"infrared_city_buildings_{self.date_now}_tile_{idx}.bim")

        with open(dotbim_path, "w", encoding="utf-8") as f:
            json.dump(dotbim_data, f, ensure_ascii=False, indent=2)

        logger.info("Tile %d saved to %s and %s", idx, geojson_path, dotbim_path)

        # 512x512 bbox in layer CRS (for OGC API)
        bbox_512 = (
            bbox_rect_layer.xMinimum(),
            bbox_rect_layer.yMinimum(),
            bbox_rect_layer.xMaximum(),
            bbox_rect_layer.yMaximum(),
        )

        # 256x256 bbox in the same CRS, centered on the tile center
        display_tile_size = 256.0
        half_disp = display_tile_size / 2.0
        bbox_256 = (
            center_x - half_disp,
            center_y - half_disp,
            center_x + half_disp,
            center_y + half_disp,
        )

        crs_authid = layer_crs.authid()

        return geojson_path, dotbim_path, bbox_512, crs_authid, bbox_256

    def _prepare_run_parameters(self):
        """Compute bbox from selection, generate tile centers and fixed wind parameters."""

        # Bbox in active layer CRS based on selected features
        w, s, e, n = self._get_selected_bbox()
        logger.info(f"Selected bbox: W={w}, S={s}, E={e}, N={n}")

        # Generate tile centers in layer CRS
        tile_centers = self._generate_tile_centers(w, s, e, n)
        logger.info("Generated %d tile centers", len(tile_centers))
        logger.info("Tile centers: %s", tile_centers)

        # Fixed wind parameters for batch run
        wind_direction = 0
        wind_speed = 15
        analysis_type = AnalysisType.WIND_SPEED

        return tile_centers, wind_direction, wind_speed, analysis_type

    def _load_api_key(self):
        """Load API key used for OGC calls (currently hard-coded for batch runs)."""

        plugin_settings_dir = os.path.join(QgsApplication.qgisSettingsDirPath(), "infrared_city_gis", "settings")
        user_file = os.path.join(plugin_settings_dir, "settings.json")

        # NOTE: For now we rely on a fixed API key here; can be wired to settings.json similarly to run_simulation dialog.
        api_key = "Rs1MoXnOUn4PPPQ3LT7JZ8LN5J5SvV615rik1JgI"
        return api_key

    def _run_batch_for_tiles(self, tile_centers, wind_direction, wind_speed, analysis_type, api_key):
        """Process each tile center: geometry selection/export, OGC run, crop and display result."""

        for idx, (center_x, center_y) in enumerate(tile_centers):
            logger.info("Processing tile center %d: %s, %s", idx, center_x, center_y)
            res = self._process_tile_center(center_x, center_y, idx)
            if not res:
                continue

            geojson_path, dotbim_path, bbox_512, crs_authid, bbox_256 = res

            logger.info(
                f"Tile {idx}: geojson={geojson_path}, dotbim={dotbim_path}, bbox_512={bbox_512}, bbox_256={bbox_256}, crs={crs_authid}"
            )

            if not api_key:
                logger.warning("Skipping simulation for tile %d: missing API key.", idx)
                continue

            try:
                logger.info("Starting wind speed OGC simulation for tile %d", idx)
                payload = get_windspeed_payload_ogc(dotbim_path, bbox_512, crs_authid, wind_direction, wind_speed)
                geotiff_path = process_ogc(payload, dotbim_path, analysis_type.value, api_key)
                logger.info("Simulation finished for tile %d", idx)

                # Crop 512x512 GeoTIFF to 256x256 around the tile center and display
                try:
                    with rasterio.open(geotiff_path) as src:
                        matrix = src.read(1)

                    cropped_matrix = crop_matrix(matrix, core_size=256)
                    sub_bbox = bbox_256

                    base_name = os.path.splitext(os.path.basename(geotiff_path))[0]
                    plugin_data_dir = os.path.dirname(geotiff_path)
                    cropped_geotiff_path = os.path.join(plugin_data_dir, f"{base_name}_crop.tif")

                    generate_geotiff(
                        cropped_matrix,
                        sub_bbox,
                        crs_authid,
                        cropped_geotiff_path,
                        simulation_type="wind-speed",
                    )

                    add_geojson_then_raster(
                        geojson_path,
                        cropped_geotiff_path,
                        analysis_type=analysis_type.value,
                        sub_analysis_type=None,
                    )
                    logger.info("Cropped Geotiff visualized for tile %d", idx)
                except Exception as e_crop:
                    logger.error("Failed to crop/display GeoTIFF for tile %d: %s", idx, e_crop)
            except Exception as e:
                logger.error("Simulation failed for tile %d: %s", idx, e)

    def accept(self):
        """Entry point when user confirms the dialog: run batch simulations for all tiles."""

        tile_centers, wind_direction, wind_speed, analysis_type = self._prepare_run_parameters()
        api_key = self._load_api_key()
        self._run_batch_for_tiles(tile_centers, wind_direction, wind_speed, analysis_type, api_key)

        super().accept()