# -*- coding: utf-8 -*-
"""
/***************************************************************************
 InfraredCityGIS
                                 A QGIS plugin
 This is a plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-10-13
        git sha              : $Format:%H$
        copyright            : (C) 2025 by infrared.city
        email                : connectors@infrared.city
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os.path

from qgis.core import Qgis
from qgis.PyQt.QtCore import QCoreApplication, QSettings, QTranslator
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

from .exceptions import InfraredAPIError

# Import the code for the dialog
from .infrared_city_fetch_geometry_dialog import InfraredCityFetchGeometryDialog
from .infrared_city_fetch_ground_materials_dialog import (
    InfraredCityFetchGroundMaterialsDialog,
)
from .infrared_city_run_multiple_simulation_dialog import (
    InfraredCityRunMultipleSimulationDialog,
)
from .infrared_city_save_auth import InfraredCitySaveAuthDialog
from .infrared_city_select_bbox_dialog import InfraredCitySelectBBoxDialog
from .infrared_city_tree_catalog_dialog import InfraredCityTreeCatalogDialog
from .infrared_logger import logger
from .services.fetch_from_registry import _load_api_key, fetch_from_registry
from .utils.helper import cleanup_old_data

_ICON_DIR = os.path.join(os.path.dirname(__file__), 'icons')


def _icon(name: str) -> str:
    """File system path to a bundled icon.

    Icons used to be addressed through Qt resource paths
    (``:/plugins/infrared_city_gis/icons/...``) backed by a ``pyrcc5``-compiled
    ``resources.py``. PyQt6 ships no resource compiler, so that module could
    not be rebuilt for QGIS 4 — and importing it pulled in ``PyQt5`` directly,
    which fails outright there. ``QIcon`` takes a plain path just as happily,
    on both Qt5 and Qt6, and a new icon needs no build step.
    """
    return os.path.join(_ICON_DIR, name)


class InfraredCityGIS:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        self.last_geojson_path = None
        self.last_dotbim_path = None
        self.bbox = None
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        self.dlg = None

        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'InfraredCityGIS_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&infrared.city GIS')

        # cleanup old data
        cleanup_old_data()

        # Refresh the model registry (visualConfigurations) on startup so that
        # colormaps reflect the latest server-side definitions. Only runs if
        # the user has already saved an API key; otherwise skipped silently
        # and will run later on save / on demand.
        #
        # The call doubles as a key check: a 401/403 here means the SAVED key
        # was rejected by the server, and initGui() greys out every action
        # except "Save API Key". Transient failures (offline, 5xx) do NOT
        # flag the key — an outage must not lock the user out of the plugin.
        self._saved_key_rejected = False
        if _load_api_key():
            try:
                _ = fetch_from_registry()
            except InfraredAPIError as e:
                if e.status_code in (401, 403):
                    self._saved_key_rejected = True
                logger.warning("Startup registry refresh failed: %s", e)
            except Exception as e:
                logger.warning("Startup registry refresh failed: %s", e)

    # noinspection PyMethodMayBeStatic

    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('InfraredCityGIS', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None,
    ):
        """Add a toolbar icon to the toolbar.

        :param icon_path: File system path to the icon for this action — see
            :func:`_icon`. Qt resource paths (``:/plugins/...``) are no longer
            used; the compiled resource module they needed cannot be rebuilt
            for Qt6.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        save_auth_icon_path = _icon('login.png')
        fetch_geometry_icon_path = _icon('get_geometry.png')
        select_bbox_icon_path = _icon('select_area.png')
        tree_icon_path = _icon('tree.svg')
        run_multiple_icon_path = _icon('run_multiple.svg')
        ground_materials_icon_path = _icon('ground_materials.png')

        # Kept as an attribute: this is the one action that must stay
        # enabled when the API key is missing or rejected (see
        # _set_authed_actions_enabled).
        self.auth_action = self.add_action(
            save_auth_icon_path,
            text=self.tr(u'Save API Key'),
            callback=self.save_api_key,
            parent=self.iface.mainWindow()
        )

        self.add_action(
            fetch_geometry_icon_path,
            text=self.tr(u'Fetch building geometry'),
            callback=self.fetch_geometry,
            parent=self.iface.mainWindow())

        self.add_action(
            ground_materials_icon_path,
            text=self.tr(u'Fetch ground materials'),
            callback=self.fetch_ground_materials,
            parent=self.iface.mainWindow()
        )

        self.add_action(
            select_bbox_icon_path,
            text=self.tr(u'Select tile'),
            callback=self.select_bbox,
            parent=self.iface.mainWindow()
        )

        self.add_action(
            tree_icon_path,
            text=self.tr(u'Tree catalog'),
            callback=self.select_tree_type,
            parent=self.iface.mainWindow()
        )

        # NOTE: the legacy single-simulation action and its
        # InfraredCityRunSimulationDialog have been removed — the "Run
        # simulation" dialog below now handles both single-tile (via the
        # "Select tile" tool + analyses.execute) and area runs, mirroring the
        # ArcGIS plugin. The "Fetch geometry from OSM" action above is kept as
        # a standalone geometry-export utility.
        self.add_action(
            run_multiple_icon_path,
            text=self.tr(u'Run simulation'),
            callback=self.run_multiple_simulations,
            parent=self.iface.mainWindow()
        )

        # Grey out everything but "Save API Key" until a key is present and
        # not known-bad. New keys are only ever saved after verification
        # (see InfraredCitySaveAuthDialog.accept); an ALREADY-saved key is
        # only locked out on a confirmed 401/403 from the startup registry
        # check above — a mere outage keeps the plugin usable.
        if not _load_api_key():
            self._set_authed_actions_enabled(False)
        elif self._saved_key_rejected:
            self._set_authed_actions_enabled(False)
            self.iface.messageBar().pushWarning(
                "InfraredCity",
                "Your saved API key was rejected by the Infrared server. "
                "Update it via 'Save API Key'. If you believe the key is "
                "correct, please contact us at connectors@infrared.city.",
            )

    def _set_authed_actions_enabled(self, enabled):
        """Enable/disable every action except "Save API Key".

        Actions are disabled while no valid API key is configured, so users
        cannot open dialogs whose API calls would only fail with auth errors.
        Only this plugin's own toolbar/menu actions are gated — QGIS itself
        is untouched. Disabled toolbar buttons still show their tooltip on
        hover, so the tooltip explains WHY the action is greyed out.
        """
        why_disabled = self.tr(
            u'Requires a valid API key — set one via "Save API Key"'
        )
        for action in self.actions:
            if action is self.auth_action:
                continue
            action.setEnabled(enabled)
            # QAction's default tooltip is its text; restore that on enable.
            action.setToolTip(action.text() if enabled else why_disabled)

    def unload(self):
        """Remove the plugin's menu items and toolbar icons, and stop polling.

        Stopping the pollers is the part that matters on **quit**: QGIS tears
        the Qt and network stacks down while static destructors run, and a
        poller still ticking can open an HTTPS connection mid-teardown —
        observed as a SIGSEGV in Qt's own SSL cleanup
        (``QSslConfigurationPrivate::deepCopyDefaultConfiguration`` on the
        QNetworkAccessManager thread). Submitted jobs continue server-side, so
        nothing is lost by stopping.
        """
        from .services.sdk_runner import _ACTIVE_POLLERS

        for poller in list(_ACTIVE_POLLERS):
            try:
                poller.shutdown()
            except Exception as e:  # never let teardown fail on a dead C++ object
                logger.warning("unload: could not stop poller: %s", e)
        _ACTIVE_POLLERS.clear()

        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&infrared.city GIS'),
                action)
            self.iface.removeToolBarIcon(action)

    def run_multiple_simulations(self):
        """Run method that performs all the real work"""

        self.dlg = InfraredCityRunMultipleSimulationDialog()

        if not getattr(self.dlg, "_init_ok", False):
            logger.warning("Multiple simulations dialog initialization failed")
            return

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec()

        if result:
            logger.info("Multiple simulations dialog closed successfully")
        else:
            logger.info("Multiple simulations dialog cancelled")

    def select_bbox(self):
        """Run method that performs all the real work"""

        self.dlg = InfraredCitySelectBBoxDialog()

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec()

        if result:

            self.last_geojson_path = getattr(self.dlg, "geojson_path", None)
            self.last_dotbim_path = getattr(self.dlg, "dotbim_path", None)
            self.bbox = getattr(self.dlg, "bbox", None)
            self.crs = getattr(self.dlg, "crs", None)

            logger.info("BBox selected successfully")
        else:
            logger.error("BBox selection cancelled")

        # When the modal dialog closes, Qt hands keyboard focus back to the
        # toolbar button that opened it, which macOS draws as a lingering
        # focus ring around the "Select tile" icon. Move focus to the map
        # canvas so the toolbar looks idle again.
        try:
            self.iface.mapCanvas().setFocus()
        except Exception:
            pass

    def select_tree_type(self):
        self.dlg = InfraredCityTreeCatalogDialog()

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec()

        if result:
            logger.info("Tree type selected successfully")
        else:
            logger.info("Tree type selection cancelled")

    def save_api_key(self):
        """Open the API key save dialog."""
        self.dlg = InfraredCitySaveAuthDialog(
            self.iface.mainWindow(),
            saved_key_rejected=self._saved_key_rejected,
        )

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec()

        if result:
            # accept() only fires after the key was verified against the
            # server AND saved — unlock the rest of the toolbar.
            self._saved_key_rejected = False
            self._set_authed_actions_enabled(True)
            logger.info("API key save dialog closed successfully (verified)")
        else:
            logger.info("API key save dialog cancelled")

    def fetch_ground_materials(self):
        """Open the selection-based ground-materials fetch dialog."""
        self.dlg = InfraredCityFetchGroundMaterialsDialog(self.iface.mainWindow())

        if not getattr(self.dlg, "_init_ok", False):
            # Preconditions failed (no API key / no selection / preview
            # error) — the dialog already showed the specific message.
            logger.info("Ground materials dialog: preconditions not met")
            return

        result = self.dlg.exec()
        if result:
            logger.info(
                "Ground materials fetched: %s",
                getattr(self.dlg, "created_layers", {}),
            )
        else:
            logger.info("Ground materials fetch cancelled")

    def fetch_geometry(self):
        """Run method that performs all the real work"""
        self.dlg = InfraredCityFetchGeometryDialog()

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec()
        # See if OK was pressed
        if result:  # OK was pressed
            self.last_geojson_path = getattr(self.dlg, "geojson_path", None)
            self.bbox = getattr(self.dlg, "bbox", None)
            self.crs = "EPSG:4326"

            if self.last_geojson_path and self.bbox:
                self.iface.messageBar().pushMessage(
                    "InfraredCity",
                    f"Fetched geometry saved to: {self.last_geojson_path} \n"
                    f"with bbox: {self.bbox}",
                    level=Qgis.Info,
                    duration=5
                )
            else:
                self.iface.messageBar().pushWarning(
                    "InfraredCity",
                    "No file path returned from fetch dialog."
                )
