# -*- coding: utf-8 -*-
"""
/***************************************************************************
 InfraredCityDialog
                                 A QGIS plugin
 This is a plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-13
        git sha              : $Format:%H$
        copyright            : (C) 2025 by infrared.city
        email                : daniel.lepold@infrared.city
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtWidgets import QMessageBox
from .infrared_logger import logger
from .visualization.display import display_geojson
from .services.fetch import fetch_geometry_from_osm

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'infrared_city_fetch_geometry_dialog.ui'))


class InfraredCityFetchGeometryDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(InfraredCityFetchGeometryDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        logger.info("Dialog loaded")
        # DEBUGGING:
        self.longitude_input.setText("16.3738189")   
        self.latitude_input.setText("48.2081743")   
 
        
        #self.label.setText("Hello from QGIS plugin dialog!")

        # Kapcsoljuk össze az OK gombot a validációs függvénnyel
        self.button_box.accepted.connect(self.accept)
        self.button_box.rejected.connect(self.reject)

    def accept(self):
        """Run fetch when OK is pressed."""
        longitude = self.longitude_input.text().strip()
        latitude = self.latitude_input.text().strip()
        bbox = self.bbox_input.text().strip()
        
        # --- Validation ---
        if not longitude or not latitude or not bbox:
            logger.warning("Missing input")
            QMessageBox.warning(self, "Missing Input", "Please fill in all fields!")
            return

        try:
            lon = float(longitude)
            lat = float(latitude)
            bbox_val = float(bbox)
        except ValueError:
            logger.error("Invalid input")
            QMessageBox.warning(self, "Invalid Input", "Coordinates and bbox must be numbers.")
            return

        # --- Fetch ---
        try:
            geojson_path, dotbim_path, bbox = fetch_geometry_from_osm(lon, lat, bbox_val)

            self.geojson_path = geojson_path
            self.dotbim_path = dotbim_path
            self.bbox=bbox

            display_geojson(geojson_path)

        except Exception as e:
            logger.error(f"Failed to fetch geometry: {e}")
            return

        super().accept()