# -*- coding: utf-8 -*-
"""
/***************************************************************************
 InfraredCityGIS
                                 A QGIS plugin
 This is a plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-10-13
        git sha              : $Format:%H$
        copyright            : (C) 2025 by infrared.city
        email                : connectors@infrared.city
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.utils import iface  
from qgis.core import Qgis
from qgis.PyQt.QtWidgets import QDialog

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .infrared_city_fetch_geometry_dialog import InfraredCityFetchGeometryDialog
from .infrared_city_run_simulation_dialog import InfraredCityRunSimulationDialog
from .infrared_city_select_bbox_dialog import InfraredCitySelectBBoxDialog
from .infrared_city_run_multiple_simulation_dialog import InfraredCityRunMultipleSimulationDialog
from .infrared_city_tree_catalog_dialog import InfraredCityTreeCatalogDialog
from .infrared_city_save_auth import InfraredCitySaveAuthDialog

import os.path
from .infrared_logger import logger
from .utils.helper import cleanup_old_data
from .services.fetch_from_registry import _load_api_key, fetch_from_registry

class InfraredCityGIS:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        self.last_geojson_path = None
        self.last_dotbim_path = None
        self.last_geotiff_path = None
        self.bbox = None
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        self.dlg = None

        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'InfraredCityGIS_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Infrared City GIS')

        # cleanup old data
        cleanup_old_data()

        # Refresh the model registry (visualConfigurations) on startup so that
        # colormaps reflect the latest server-side definitions. Only runs if
        # the user has already saved an API key; otherwise skipped silently
        # and will run later on save / on demand.
        if _load_api_key():
            try:
                _ = fetch_from_registry()
            except Exception as e:
                logger.warning("Startup registry refresh failed: %s", e)

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('InfraredCityGIS', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        save_auth_icon_path = ':/plugins/infrared_city_gis/icons/login.png'
        fetch_geometry_icon_path = ':/plugins/infrared_city_gis/icons/get_geometry.png'
        select_bbox_icon_path = ':/plugins/infrared_city_gis/icons/select_area.png'
        tree_icon_path = ':/plugins/infrared_city_gis/icons/tree.svg'
        run_single_icon_path = ':/plugins/infrared_city_gis/icons/run_single.svg'
        run_multiple_icon_path = ':/plugins/infrared_city_gis/icons/run_multiple.svg'
        
        self.add_action(
            save_auth_icon_path,
            text=self.tr(u'Save API Key'),
            callback=self.save_api_key,
            parent=self.iface.mainWindow()
        )
        
        self.add_action(
            fetch_geometry_icon_path,
            text=self.tr(u'Fetch geometry from OSM'),
            callback=self.fetch_geometry,
            parent=self.iface.mainWindow())
        
        self.add_action(
            select_bbox_icon_path,
            text=self.tr(u'Select bbox by center'),
            callback=self.select_bbox,
            parent=self.iface.mainWindow()
        )
        
        self.add_action(
            tree_icon_path,
            text=self.tr(u'Tree catalog'),
            callback=self.select_tree_type,
            parent=self.iface.mainWindow()
        )
        
        self.add_action(
            run_single_icon_path,
            text=self.tr(u'Run simulation'),
            callback=self.run_simulation,
            parent=self.iface.mainWindow()
        )

        self.add_action(
            run_multiple_icon_path,
            text=self.tr(u'Run multiple simulations'),
            callback=self.run_multiple_simulations,
            parent=self.iface.mainWindow()
        )

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Infrared City GIS'),
                action)
            self.iface.removeToolBarIcon(action)

    def run_multiple_simulations(self):
        """Run method that performs all the real work"""

        self.dlg = InfraredCityRunMultipleSimulationDialog()
        
        if not getattr(self.dlg, "_init_ok", False):
            logger.warning("Multiple simulations dialog initialization failed")
            return

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()

        if result:
            logger.info("Multiple simulations dialog closed successfully")
        else:
            logger.info("Multiple simulations dialog cancelled")
        
    
    def select_bbox(self):
        """Run method that performs all the real work"""

        self.dlg = InfraredCitySelectBBoxDialog()

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()

        if result:

            self.last_geojson_path = getattr(self.dlg, "geojson_path", None)
            self.last_dotbim_path = getattr(self.dlg, "dotbim_path", None)
            self.bbox = getattr(self.dlg,"bbox",None)
            self.crs = getattr(self.dlg,"crs",None)


            logger.info("BBox selected successfully")
        else:
            logger.error("BBox selection cancelled")
    
    
    def select_tree_type(self):
        self.dlg = InfraredCityTreeCatalogDialog()
        
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        
        if result:
            logger.info("Tree type selected successfully")
        else:
            logger.info("Tree type selection cancelled")
    
    def save_api_key(self):
        """Open the API key save dialog."""
        self.dlg = InfraredCitySaveAuthDialog(self.iface.mainWindow())
        
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        
        if result:
            logger.info("API key save dialog closed successfully")
        else:
            logger.info("API key save dialog cancelled")
    
    def fetch_geometry(self):
        """Run method that performs all the real work"""
        self.dlg = InfraredCityFetchGeometryDialog()

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:  # OK was pressed
                self.last_geojson_path = getattr(self.dlg, "geojson_path", None)
                self.last_dotbim_path = getattr(self.dlg, "dotbim_path", None)
                self.bbox = getattr(self.dlg,"bbox",None)
                self.crs = "EPSG:4326"

                if self.last_geojson_path and self.bbox and self.last_dotbim_path:
                    self.iface.messageBar().pushMessage(
                        "InfraredCity",
                        f"Fetched geometry saved to: {self.last_geojson_path} \n "
                        f"and .bim to {self.last_dotbim_path} \n"
                        f"with bbox: {self.bbox}",
                        level=Qgis.Info,
                        duration=5
                    )
                else:
                    self.iface.messageBar().pushWarning(
                        "InfraredCity",
                        "No file path returned from fetch dialog."
                    )
        
    def run_simulation(self):
        """Run method that performs all the real work"""
        if not self.last_geojson_path or not self.last_dotbim_path or not self.bbox or not self.crs:
            self.iface.messageBar().pushWarning("InfraredCity", "Please select geometry first.")
            return

        logger.info("Simulation dialog creation started")
        self.dlg = InfraredCityRunSimulationDialog(dotbim_path=self.last_dotbim_path,geojson_path=self.last_geojson_path,bbox=self.bbox,crs=self.crs)
        logger.info("Simulation dialog created")

        if not self.dlg._init_ok:
            return

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            logger.info("Simulation dialog closed")

            self.last_geotiff_path = getattr(self.dlg, "geotiff_path", None)

            if self.last_geotiff_path:
                self.iface.messageBar().pushMessage(
                        "InfraredCity",
                        f"Simulation result saved to geotiff: {self.last_geotiff_path}",
                        level=Qgis.Info,
                        duration=5
                    )

            pass
