# -*- coding: utf-8 -*-
"""
/***************************************************************************
 InfraredCityDialog
                                 A QGIS plugin
 This is a plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-13
        git sha              : $Format:%H$
        copyright            : (C) 2025 by infrared.city
        email                : connectors@infrared.city
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtWidgets, uic
from qgis.PyQt.QtWidgets import QMessageBox

from .infrared_logger import logger
from .services.fetch import fetch_geometry_from_infrared
from .services.secret_manager import get_api_key
from .visualization.display import display_geojson

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'infrared_city_fetch_geometry_dialog.ui'))


class InfraredCityFetchGeometryDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(InfraredCityFetchGeometryDialog, self).__init__(parent)

        self.setupUi(self)
        logger.info("Dialog loaded")

        self.button_box.accepted.connect(self.accept)
        self.button_box.rejected.connect(self.reject)

    def accept(self):
        """Run fetch when OK is pressed."""
        longitude = self.longitude_input.text().strip()
        latitude = self.latitude_input.text().strip()

        # --- Validation ---
        if not longitude or not latitude:
            logger.warning("Missing input")
            QMessageBox.warning(self, "Missing Input", "Please fill in all fields!")
            return

        try:
            lon = float(longitude)
            lat = float(latitude)
        except ValueError:
            logger.error("Invalid input")
            QMessageBox.warning(self, "Invalid Input", "Coordinates must be numbers.")
            return

        api_key = get_api_key()
        if not api_key:
            QMessageBox.warning(
                self, "No API Key",
                "Fetching building geometry requires an Infrared City API key.\n"
                "Please save your API key first (Save API Key).",
            )
            return

        # Area size in metres comes from the (disabled) spinbox — fixed at the
        # 1 km × 1 km default (1024 m) the .ui ships with.
        size_m = float(self.bbox_input.value())

        # --- Fetch a 1 km × 1 km area of building footprints as GeoJSON ---
        try:
            geojson_path, bbox, error = fetch_geometry_from_infrared(lon, lat, size_m, api_key)

            if error:
                logger.error("Geometry fetch failed for lon=%s lat=%s: %s", lon, lat, error)
                QMessageBox.critical(
                    self, "Fetch Failed",
                    f"Failed to fetch building geometry.\n\n{error}.\n\n"
                    "Check your API key/subscription and network, then try again.\n\n"
                    "See the plugin log for details.",
                )
                return

            if not geojson_path or not bbox:
                # Request succeeded but there are no buildings here — not an error.
                logger.info("No buildings found for lon=%s lat=%s", lon, lat)
                QMessageBox.information(
                    self, "No Buildings",
                    "No buildings were found in the 1 km × 1 km area at these "
                    "coordinates. Try a different location.",
                )
                return

            self.geojson_path = geojson_path
            self.bbox = bbox

            display_geojson(geojson_path)

        except Exception as e:
            logger.error(f"Failed to fetch geometry: {e}")
            QMessageBox.critical(
                self, "Fetch Error",
                f"Failed to fetch geometry.\n\n{e}\n\nSee the plugin log for details.",
            )
            return

        super().accept()
