# -*- coding: utf-8 -*-
"""
/***************************************************************************
 InfraredCityDialog
                                 A QGIS plugin
 This is a plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-13
        git sha              : $Format:%H$
        copyright            : (C) 2025 by infrared.city
        email                : daniel.lepold@infrared.city
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtWidgets import QMessageBox
from .client import (
    run_wind_speed, run_pwc, run_utci, run_tcs, run_solar_analyses, run_shadow_mask
)
from .services.fetch import fetch_weather_file_names
from .services.geometry import get_center_lon_lat_from_bbox
from .infrared_logger import logger
import json
from qgis.core import QgsApplication
from .models.analysis import AnalysisType, PedestrianWindComfortType, ThermalComfortStatisticsType
from .models.timeframes_parser import SeasonalTimeFrameConfig, DailyTimeFrameConfig,DailyTimeFrameConfigUTCI, validate_weather_filename, MonthConfig
from .models.weather_files import WeatherFile
from qgis.PyQt.QtCore import QDateTime  # ha még nincs importálva
from datetime import datetime 

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'infrared_city_run_simulation_dialog.ui'))


class InfraredCityRunSimulationDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None, dotbim_path=None, geojson_path=None ,bbox=None,crs=None):
        super().__init__(parent)
        self.setupUi(self)

        self.dotbim_path = dotbim_path
        self.geojson_path = geojson_path
        self.geotiff_path = None
        self.bbox = bbox
        self.crs = crs
        self.colors = None
        self.weather_file_names = []
        self.analysis_type_dropdown.clear()
        for t in AnalysisType:
            self.analysis_type_dropdown.addItem(str(t), t)
        self.analysis_type_dropdown.currentTextChanged.connect(self.on_analysis_changed)
        self.analysis_type = None
        self.api_key = None
        
        self.button_box.accepted.connect(self.accept)
        self.button_box.rejected.connect(self.reject)

        if self.analysis_type_dropdown.count() > 0:
            self.analysis_type_dropdown.setCurrentIndex(0)
            self.on_analysis_changed(self.analysis_type_dropdown.currentText())

        
        # Plugin data dir + user.json
        plugin_data_dir = os.path.join(QgsApplication.qgisSettingsDirPath(), "infrared_city_gis", "settings")
        user_file = os.path.join(plugin_data_dir, "user.json")

        if os.path.exists(user_file):
            try:
                with open(user_file, "r", encoding="utf-8") as f:
                    data = json.load(f)
                    api_key = data.get("api-key", "")
                    self.api_key_input.setText(api_key)
                    self.api_key = api_key
                    logger.info(f"Loaded API key from user.json: {api_key}")
            except Exception as e:
                logger.warning(f"Could not read API key: {e}")
                QMessageBox.warning(self, "Invalid API Key", "Invalid API key. Please check the input values.")



        logger.info("Dialog loaded")
        logger.info("Dotbim path: %s", self.dotbim_path)
        logger.info("Geojson path: %s", self.geojson_path)
        logger.info("Bbox: %s", self.bbox)
        logger.info("CRS: %s", self.crs)



    def on_analysis_changed(self, text):
        current = self.analysis_type_dropdown.currentData()
        
        # Get weather file names

        if self.bbox is not None and self.api_key and not self.weather_file_names:
            lon, lat = get_center_lon_lat_from_bbox(self.bbox) 
            self.weather_file_names = fetch_weather_file_names(lon, lat, 100, self.api_key)
        
        # Switch stacked pages instead of toggling visibility
        try:
            if current == AnalysisType.WIND_SPEED:
                self.content_stack.setCurrentIndex(0)
            elif current == AnalysisType.PEDESTRIAN_WIND_COMFORT:
                self.content_stack.setCurrentIndex(1)
            elif current == AnalysisType.THERMAL_COMFORT_INDEX:
                self.content_stack.setCurrentIndex(2)
            elif current == AnalysisType.THERMAL_COMFORT_STATISTICS:
                self.content_stack.setCurrentIndex(3)
            elif current == AnalysisType.SOLAR_RADIATION:
                self.content_stack.setCurrentIndex(4)
            elif current == AnalysisType.DAYLIGHT_AVAILABILITY:
                self.content_stack.setCurrentIndex(5)
            elif current == AnalysisType.DIRECT_SUN_HOURS:
                self.content_stack.setCurrentIndex(6)
            elif current == AnalysisType.SKY_VIEW_FACTORS:
                self.content_stack.setCurrentIndex(7)
            elif current == AnalysisType.SHADOW_MASK:
                self.content_stack.setCurrentIndex(8)
        except AttributeError:
            # Fallback for older UI without stacked widget
            try:
                self.group_wind_speed.setVisible(current == AnalysisType.WIND_SPEED)
                self.group_pedestrian_wind_comfort.setVisible(current == AnalysisType.PEDESTRIAN_WIND_COMFORT)
                self.group_thermal_comfort.setVisible(current == AnalysisType.THERMAL_COMFORT_INDEX)
                self.group_thermal_comfort_statistics.setVisible(current == AnalysisType.THERMAL_COMFORT_STATISTICS)
                self.group_solar_radiation.setVisible(current == AnalysisType.SOLAR_RADIATION)
                self.group_daylight_availability.setVisible(current == AnalysisType.DAYLIGHT_AVAILABILITY)
                self.group_direct_sun_hours.setVisible(current == AnalysisType.DIRECT_SUN_HOURS)
                self.group_sky_view_factors.setVisible(current == AnalysisType.SKY_VIEW_FACTORS)
                self.group_shadow_mask.setVisible(current == AnalysisType.SHADOW_MASK)
            except AttributeError as e:
                logger.error("Failed to update group visibility: %s", str(e), exc_info=True)

        if current == AnalysisType.PEDESTRIAN_WIND_COMFORT:
            try:
                self.weather_file_input_pwc.setEditable(True)
                self.weather_file_input_pwc.clear()

                for w in self.weather_file_names:
                    self.weather_file_input_pwc.addItem(w, w)

                self.pwc_type_dropdown.clear()
                for s in PedestrianWindComfortType:
                    self.pwc_type_dropdown.addItem(str(s), s)

                self.season_dropdown_pwc.clear()
                for season in SeasonalTimeFrameConfig:
                    self.season_dropdown_pwc.addItem(season.value, season)

                self.hours_dropdown_pwc.clear()
                for hours in DailyTimeFrameConfig:
                    self.hours_dropdown_pwc.addItem(hours.value, hours)
            except Exception as e:
                logger.error("Failed to populate PWC dialog elements: %s", str(e), exc_info=True)
        
        if current == AnalysisType.THERMAL_COMFORT_INDEX:
            try:
                self.weather_file_input_tci.setEditable(True)
                self.weather_file_input_tci.clear()

                for w in self.weather_file_names:
                    self.weather_file_input_tci.addItem(w, w)

                self.legend_min_input_tci.setEnabled(False)
                self.legend_max_input_tci.setEnabled(False)

                self.legend_min_enable_tci.toggled.connect(
                    self.legend_min_input_tci.setEnabled
                )
                self.legend_max_enable_tci.toggled.connect(
                    self.legend_max_input_tci.setEnabled
                )

                self.month_dropdown_tci.clear()
                for month in MonthConfig:
                    self.month_dropdown_tci.addItem(month.value, month)

                self.hours_dropdown_tci.clear()
                for hours in DailyTimeFrameConfigUTCI:
                    self.hours_dropdown_tci.addItem(hours.value, hours)
            except AttributeError as e:
                logger.error("Failed to populate TCI dialog elements: %s", str(e), exc_info=True)

        if current == AnalysisType.THERMAL_COMFORT_STATISTICS:
            try:
                self.weather_file_input_tcs.setEditable(True)
                self.weather_file_input_tcs.clear()

                for w in self.weather_file_names:
                    self.weather_file_input_tcs.addItem(w, w)

                self.season_dropdown_tcs.clear()
                for season in SeasonalTimeFrameConfig:
                    self.season_dropdown_tcs.addItem(season.value, season)

                self.hours_dropdown_tcs.clear()
                for hours in DailyTimeFrameConfig:
                    self.hours_dropdown_tcs.addItem(hours.value, hours)

                self.tcs_type_dropdown.clear()
                for tcs_type in ThermalComfortStatisticsType:
                    self.tcs_type_dropdown.addItem(tcs_type.value, tcs_type)
            except Exception as e:
                logger.error("Failed to populate TCS dialog elements: %s", str(e), exc_info=True)

        if current == AnalysisType.SOLAR_RADIATION:
            try:
                self.weather_file_input_sr.setEditable(True)
                self.weather_file_input_sr.clear()

                for w in self.weather_file_names:
                    self.weather_file_input_sr.addItem(w, w)

                self.month_dropdown_sr.clear()
                for month in MonthConfig:
                    self.month_dropdown_sr.addItem(month.value, month)

                self.hours_dropdown_sr.clear()
                for hours in DailyTimeFrameConfig:
                    self.hours_dropdown_sr.addItem(hours.value, hours)
            except Exception as e:
                logger.error("Failed to populate solar radiation dialog elements: %s", str(e), exc_info=True)

        if current == AnalysisType.DAYLIGHT_AVAILABILITY:
            try:
                self.month_dropdown_da.clear()
                for month in MonthConfig:
                    self.month_dropdown_da.addItem(month.value, month)

                self.hours_dropdown_da.clear()
                for hours in DailyTimeFrameConfig:
                    self.hours_dropdown_da.addItem(hours.value, hours)
            except Exception as e:
                logger.error("Failed to populate daylight availability dialog elements: %s", str(e), exc_info=True)

        if current == AnalysisType.DIRECT_SUN_HOURS:
            try:
                self.month_dropdown_dsh.clear()
                for month in MonthConfig:
                    self.month_dropdown_dsh.addItem(month.value, month)

                self.hours_dropdown_dsh.clear()
                for hours in DailyTimeFrameConfig:
                    self.hours_dropdown_dsh.addItem(hours.value, hours)
            except Exception as e:
                logger.error("Failed to populate direct sun hours dialog elements: %s", str(e), exc_info=True)

        if current == AnalysisType.SHADOW_MASK:
            try:
                self.datetime_input_sm.setDateTime(QDateTime.currentDateTime())
            except Exception as e:
                logger.error("Failed to populate shadow mask dialog elements: %s", str(e), exc_info=True)
    
    def accept(self):
        logger.info("\n ✨ ✨ ✨ ✨ ✨ ✨ ✨ SIMULATION RUN START ✨ ✨ ✨ ✨ ✨ ✨ ✨")

        logger.info(f"Accept called. Sender: {self.sender()}")
        if not self.dotbim_path or not os.path.exists(self.dotbim_path):
            logger.warning("No geometry fetched. Please fetch geometry first.")
            QMessageBox.warning(self, "Missing Geometry", "Please fetch geometry first.")
            return

        self.analysis_type = self.analysis_type_dropdown.currentData()
        self.sub_analysis_type = None


        plugin_data_dir = os.path.join(QgsApplication.qgisSettingsDirPath(), "infrared_city_gis", "settings")
        os.makedirs(plugin_data_dir, exist_ok=True)
        user_file = os.path.join(plugin_data_dir, "user.json")

        self.api_key = self.api_key_input.text().strip()
        if self.api_key:
            try:
                with open(user_file, "w", encoding="utf-8") as f:
                    json.dump({"api-key": self.api_key}, f, indent=2)
                    logger.info("API key saved successfully.")
            except Exception as e:
                logger.error(f"Failed to save API key: {e}")
        else:
            logger.warning("API key is empty. Please fill in the API key.")
            QMessageBox.warning(self, "Missing API Key", "Please fill in the API key.")
            return


        if self.analysis_type == AnalysisType.WIND_SPEED:
            # Validation
            wind_speed = self.wind_speed_input.value()
            wind_direction = self.wind_direction_input.value()
            
            if  (wind_speed <= 0 or wind_direction < 0 or wind_direction > 360):
                logger.warning("Invalid parameters. Please check the input values.")
                QMessageBox.warning(self, "Invalid Parameters", "Wind speed must be >0 and direction between 0-360°.")
                return

            # Simulation
            self.geotiff_path = run_wind_speed(
                geojson_path=self.geojson_path,
                dotbim_path=self.dotbim_path, 
                bbox=self.bbox, 
                crs=self.crs, 
                wind_direction=wind_direction, 
                wind_speed=wind_speed, 
                api_key=self.api_key, 
                analysis_type=self.analysis_type.value
            )
            if not self.geotiff_path:
                logger.error("Wind speed simulation failed to produce a geotiff path.")
                QMessageBox.warning(self, "Simulation Failed", "Wind speed simulation failed to produce a result.")
                return
        elif self.analysis_type == AnalysisType.PEDESTRIAN_WIND_COMFORT:
            # Validation
            try:
                pwc_type = self.pwc_type_dropdown.currentData()
                self.sub_analysis_type = pwc_type
                selected_season = self.season_dropdown_pwc.currentData()   
                selected_hours = self.hours_dropdown_pwc.currentData()
                weather_file = self.weather_file_input_pwc.currentText().strip()
                logger.info(f"Weather file: {weather_file}")

                if not validate_weather_filename(weather_file):
                    logger.warning("Invalid weather file name. Please check the input values.")
                    QMessageBox.warning(
                        self,
                        "Invalid Weather File",
                        "Invalid weather file name. Please check the input values."
                    )
                    return

            except AttributeError:
                logger.warning("Missing input")
                QMessageBox.warning(self, "Missing Input", "Please fill in all fields!")
                return

            # Simulation
            self.geotiff_path = run_pwc(
                geojson_path=self.geojson_path,
                dotbim_path=self.dotbim_path, 
                bbox=self.bbox, 
                crs=self.crs, 
                sub_analysis_type=pwc_type.value, 
                season=selected_season.value, 
                hours=selected_hours.value, 
                weather_file_name=weather_file, 
                api_key=self.api_key, 
                analysis_type=self.analysis_type.value
            )
            
            if not self.geotiff_path:
                logger.error("PWC simulation failed to produce a geotiff path.")
                QMessageBox.warning(self, "Simulation Failed", "PWC simulation failed to produce a result.")
                return 
        elif self.analysis_type == AnalysisType.THERMAL_COMFORT_INDEX:
            # Validation
            try:
                selected_month = self.month_dropdown_tci.currentData()      
                selected_hours = self.hours_dropdown_tci.currentData()
                if self.legend_min_enable_tci.isChecked():
                    selected_legend_min = self.legend_min_input_tci.value()
                else:
                    selected_legend_min = None
                if self.legend_max_enable_tci.isChecked():
                    selected_legend_max = self.legend_max_input_tci.value()
                else:
                    selected_legend_max = None

                weather_file = self.weather_file_input_tci.currentText().strip()
                logger.info(f"Weather file: {weather_file}")

                if not validate_weather_filename(weather_file):
                    logger.warning("Invalid weather file name. Please check the input values.")
                    QMessageBox.warning(
                        self,
                        "Invalid Weather File",
                        "Invalid weather file name. Please check the input values."
                    )
                    return

            except AttributeError:
                logger.warning(f"Missing input, Selected season and hours are required.")
                QMessageBox.warning(self, "Missing Input", "Selected season and hours are required.")
                selected_legend_min = None
                selected_legend_max = None
                return
            
            # Simulation
            self.geotiff_path = run_utci(
                geojson_path=self.geojson_path,
                dotbim_path=self.dotbim_path,
                bbox=self.bbox,
                crs=self.crs,
                month=selected_month.number,
                hours=selected_hours.value,
                weather_file_name=weather_file,
                api_key=self.api_key,
                analysis_type=self.analysis_type.value,
                legend_min=selected_legend_min,
                legend_max=selected_legend_max
            )

            if self.geotiff_path is None:
                logger.warning("Geotiff path is None, simulation failed")
                QMessageBox.warning(self, "Simulation Failed", "Simulation failed. Please check the logs for more details.")
                return
        elif self.analysis_type == AnalysisType.THERMAL_COMFORT_STATISTICS:
            # Validation
            try:
                selected_season = self.season_dropdown_tcs.currentData()
                selected_hours = self.hours_dropdown_tcs.currentData()
                selected_tcs_type = self.tcs_type_dropdown.currentData()

                weather_file = self.weather_file_input_tcs.currentText().strip()
                logger.info(f"Weather file: {weather_file}")

                if not validate_weather_filename(weather_file):
                    logger.warning("Invalid weather file name. Please check the input values.")
                    QMessageBox.warning(
                        self,
                        "Invalid Weather File",
                        "Invalid weather file name. Please check the input values."
                    )   
            except AttributeError:
                logger.warning("Missing input. TCS type is required.")
                QMessageBox.warning(self, "Missing Input", "TCS type is required.")
                return

            # Simulation
            self.geotiff_path = run_tcs(
                geojson_path=self.geojson_path,
                dotbim_path=self.dotbim_path,
                bbox=self.bbox,
                crs=self.crs,
                season=selected_season.value,
                hours=selected_hours.value,
                weather_file_name=weather_file,
                api_key=self.api_key,
                analysis_type=self.analysis_type.value,
                sub_analysis_type=selected_tcs_type.value
            )

            if self.geotiff_path is None:
                logger.warning("Geotiff path is None, simulation failed")
                QMessageBox.warning(self, "Simulation Failed", "Simulation failed. Please check the logs for more details.")
                return
        elif self.analysis_type == AnalysisType.SOLAR_RADIATION:
             # Validation
            try:
                selected_month = self.month_dropdown_sr.currentData()      
                selected_hours = self.hours_dropdown_sr.currentData()
                

                weather_file = self.weather_file_input_sr.currentText().strip()
                logger.info(f"Weather file: {weather_file}")

                if not validate_weather_filename(weather_file):
                    logger.warning("Invalid weather file name. Please check the input values.")
                    QMessageBox.warning(
                        self,
                        "Invalid Weather File",
                        "Invalid weather file name. Please check the input values."
                    )
                    return

            except AttributeError:
                logger.warning(f"Missing input, Selected month and hours are required.")
                QMessageBox.warning(self, "Missing Input", "Selected month and hours are required.")
                return
            
            # Simulation
            self.geotiff_path = run_solar_analyses(
                geojson_path=self.geojson_path,
                dotbim_path=self.dotbim_path,
                bbox=self.bbox,
                crs=self.crs,
                month=selected_month.number,
                hours=selected_hours.value,
                weather_file_name=weather_file,
                api_key=self.api_key,
                analysis_type=self.analysis_type.value
            )

            if self.geotiff_path is None:
                logger.warning("Geotiff path is None, simulation failed")
                QMessageBox.warning(self, "Simulation Failed", "Simulation failed. Please check the logs for more details.")
                return
        elif self.analysis_type == AnalysisType.DAYLIGHT_AVAILABILITY:
            try:
                selected_month = self.month_dropdown_da.currentData()      
                selected_hours = self.hours_dropdown_da.currentData()

            except AttributeError:
                logger.warning(f"Missing input, Selected month and hours are required.")
                QMessageBox.warning(self, "Missing Input", "Selected month and hours are required.")
                return
            
            # Simulation
            self.geotiff_path = run_solar_analyses(
                geojson_path=self.geojson_path,
                dotbim_path=self.dotbim_path,
                bbox=self.bbox,
                crs=self.crs,
                month=selected_month.number,
                hours=selected_hours.value,
                weather_file_name=None,
                api_key=self.api_key,
                analysis_type=self.analysis_type.value
            )

            if self.geotiff_path is None:
                logger.warning("Geotiff path is None, simulation failed")
                QMessageBox.warning(self, "Simulation Failed", "Simulation failed. Please check the logs for more details.")
                return
        elif self.analysis_type == AnalysisType.DIRECT_SUN_HOURS:
            try:
                selected_month = self.month_dropdown_dsh.currentData()      
                selected_hours = self.hours_dropdown_dsh.currentData()

            except AttributeError:
                logger.warning(f"Missing input, Selected month and hours are required.")
                QMessageBox.warning(self, "Missing Input", "Selected month and hours are required.")
                return
            
            # Simulation
            self.geotiff_path = run_solar_analyses(
                geojson_path=self.geojson_path,
                dotbim_path=self.dotbim_path,
                bbox=self.bbox,
                crs=self.crs,
                month=selected_month.number,
                hours=selected_hours.value,
                weather_file_name=None,
                api_key=self.api_key,
                analysis_type=self.analysis_type.value
            )

            if self.geotiff_path is None:
                logger.warning("Geotiff path is None, simulation failed")
                QMessageBox.warning(self, "Simulation Failed", "Simulation failed. Please check the logs for more details.")
                return
        elif self.analysis_type == AnalysisType.SKY_VIEW_FACTORS:

            self.geotiff_path = run_solar_analyses(
                geojson_path=self.geojson_path,
                dotbim_path=self.dotbim_path,
                bbox=self.bbox,
                crs=self.crs,
                month=None,
                hours=None,
                weather_file_name=None,
                api_key=self.api_key,
                analysis_type=self.analysis_type.value
            )

            if self.geotiff_path is None:
                logger.warning("Geotiff path is None, simulation failed")
                QMessageBox.warning(self, "Simulation Failed", "Simulation failed. Please check the logs for more details.")
                return    
        elif self.analysis_type == AnalysisType.SHADOW_MASK:   
            try:
                selected_datetime = self.datetime_input_sm.dateTime().toPyDateTime()
            except AttributeError:
                logger.warning(f"Missing input, Selected datetime is required.")
                QMessageBox.warning(self, "Missing Input", "Selected datetime is required.")
                return
            
            datetime_str = selected_datetime.strftime("%Y-%m-%dT%H:%M:%S+02:00")

            self.geotiff_path = run_shadow_mask(
                geojson_path=self.geojson_path,
                dotbim_path=self.dotbim_path,
                bbox=self.bbox,
                crs=self.crs,
                datetime=datetime_str,
                api_key=self.api_key,
                analysis_type=self.analysis_type.value
            )

            if self.geotiff_path is None:
                logger.warning("Geotiff path is None, simulation failed")
                QMessageBox.warning(self, "Simulation Failed", "Simulation failed. Please check the logs for more details.")
                return    
        super().accept()