# -*- coding: utf-8 -*-
"""
/***************************************************************************
 InfraredCityDialog
                                 A QGIS plugin
 This is a plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-13
        git sha              : $Format:%H$
        copyright            : (C) 2025 by infrared.city
        email                : connectors@infrared.city
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from infrared_sdk import InfraredClient
from qgis.core import Qgis
from qgis.PyQt import QtWidgets, uic
from qgis.PyQt.QtWidgets import QMessageBox
from qgis.utils import iface

from .exceptions import InfraredAPIError
from .infrared_logger import logger
from .models.analysis import (
    AnalysisType,
    PedestrianWindComfortType,
    ThermalComfortStatisticsType,
)
from .models.timeframes_parser import (
    DailyTimeFrameConfig,
    DailyTimeFrameConfigUTCI,
    MonthConfig,
    SeasonalTimeFrameConfig,
)
from .services import single_tile_selection
from .services.fetch import fetch_weather_file_names
from .services.geometry import (
    create_wgs84_geojson_polygon_from_selection,
    get_center_lon_lat_from_bbox,
    get_selected_bbox,
    get_selected_crs,
)
from .services.ground_materials import (
    ground_material_layers,
    has_ground_material_support,
    validate_ground_material_layers,
)
from .services.qgis_area_buildings import collect_qgis_area_buildings
from .services.sdk_runner import run_sdk_area_async
from .services.sdk_single_tile import run_sdk_single_tile_async
from .services.secret_manager import get_api_key
from .services.tree_layer_picker import (
    has_tree_support,
    populate_tree_layer_dropdown,
    selected_tree_layer,
    update_tree_layer_enabled,
)
from .services.tree_validation import validate_tree_layer

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'infrared_city_run_simulation_dialog.ui'))


class InfraredCityRunMultipleSimulationDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)

        self._init_ok = False

        self.dotbim_path = None
        self.geojson_path = None
        self.geotiff_path = None
        self.colors = None
        self.analysis_type_dropdown.clear()
        for t in AnalysisType:
            self.analysis_type_dropdown.addItem(str(t), t)
        self.analysis_type_dropdown.currentTextChanged.connect(self.on_analysis_changed)
        self.analysis_type = None
        self.min_legend_value = None
        self.max_legend_value = None
        self.api_key = None
        self.polygon = None
        self.tile_count = None
        self.weather_file_names = []
        # Per-analysis uploaded EPW paths ({AnalysisType: path}); set by the
        # "Upload EPW…" controls and read by build_sdk_payload.
        self._epw_paths = {}

        # ArcGIS-style mode detection: if the "Select tile" tool stored a
        # one-shot single-tile selection, peek at it and run that single
        # 512×512 m tile via analyses.execute (1 tile ≈ 10 tokens). Otherwise
        # fall back to area mode driven by the current QGIS feature selection.
        #
        # We *peek* rather than *consume* here: closing the dialog without
        # running a simulation must leave single-tile mode intact, so
        # re-opening (while the tile selection is still active) stays in
        # single-tile mode. The pending selection is cleared only after a
        # simulation is actually submitted — see accept().
        self.is_single_tile = False
        _sel = single_tile_selection.peek()
        if _sel is not None:
            self.is_single_tile = True
            self.polygon = _sel.polygon
            self.bbox = list(_sel.bbox)
            self.crs = _sel.crs
            self.tile_count = 1
            logger.info(
                "Single-tile mode: 1 tile (512×512 m), center=(%.6f, %.6f), "
                "%d buildings highlighted at pick time",
                _sel.center_lon, _sel.center_lat, _sel.building_count,
            )
        else:
            try:
                w, s, e, n = get_selected_bbox()
                self.bbox = [w, s, e, n]
                self.crs = get_selected_crs()

                iface.messageBar().pushMessage(
                    "InfraredCity",
                    f"Layer CRS is the following: {self.crs}",
                    level=Qgis.Info,
                    duration=7
                )

            except Exception as e:
                logger.error(f"Failed to get selected bbox: {e}")
                QMessageBox.warning(self, "Invalid selection", "Invalid selection please select geometry.")
                self.reject()
                return

        self.button_box.accepted.connect(self.accept)
        self.button_box.rejected.connect(self.reject)

        # Populate the "Tree layer" dropdown from the current project; the
        # subsequent on_analysis_changed call will grey it out if either
        # there are no candidate layers or the analysis doesn't support
        # vegetation.
        try:
            populate_tree_layer_dropdown(self.tree_layer_dropdown)
        except AttributeError:
            # Older .ui without the tree_layer_dropdown widget — fall back
            # silently rather than failing the whole dialog.
            logger.warning("tree_layer_dropdown not present in dialog — skipping")

        # Tree-type mode: by default each tree is typed from its own OSM tags
        # (species/genus/leaf_type) — matching a registry species for a precise
        # mesh, else an archetype server-side. The user can opt into the
        # tree-catalog override to force one type on every tree instead.
        self.use_tree_catalog_type = False
        try:
            self.tree_layer_dropdown.currentIndexChanged.connect(self._revalidate_trees)
            self.use_catalog_checkbox.toggled.connect(self._on_use_catalog_toggled)
        except AttributeError:
            pass  # older .ui without the new tree-validation widgets

        # Ground materials: one checkable row per ground-* layer in the
        # project (created by the Fetch Ground Materials dialog or drawn by
        # hand), plus an auto-fetch option that pulls Infrared's own ground
        # materials at submit time and ignores the layers. The whole section
        # hides for analyses that don't use surface materials (wind, PWC,
        # SVF).
        self._ground_layers = {}
        self.use_infrared_ground_materials = False
        try:
            self._populate_ground_materials()
            self.ground_materials_list.itemChanged.connect(
                self._on_ground_item_changed
            )
            self.use_infrared_ground_checkbox.toggled.connect(
                self._on_use_infrared_ground_toggled
            )
        except AttributeError:
            pass  # older .ui without the ground-material widgets

        # Add the "Upload EPW…" controls to the weather-based analysis pages.
        self._setup_epw_uploads()

        if self.analysis_type_dropdown.count() > 0:
            self.analysis_type_dropdown.setCurrentIndex(0)
            self.on_analysis_changed(self.analysis_type_dropdown.currentText())

        # Load API key from QSettings (or INFRARED_API_KEY env var) via the
        # secret_manager. The legacy settings/user.json file is no longer
        # consulted — the Save API Key dialog writes only to QSettings.
        try:
            self.api_key = get_api_key()
            if self.api_key:
                logger.info("API key loaded")
        except Exception as e:
            logger.warning("Could not read API key: %s", e)

        if not self.api_key:
            QMessageBox.warning(
                self,
                "Missing API Key",
                "No API key found. Please save your API key first via the 'Save API Key' menu."
            )
            self.reject()
            return

        if self.is_single_tile:
            # Polygon already set from the tile selection; skip preview_area /
            # tiling entirely — the single tile is submitted via
            # analyses.execute so the 512 m box is never split into overlapping
            # 256 m-step tiles (which would multiply the token cost).
            self.setWindowTitle("Run Simulation — single tile (512×512 m) · 1 tile · ~10 tokens")
            logger.info("Dialog loaded in single-tile mode")
        else:
            try:

                client = InfraredClient(api_key=self.api_key)
                self.polygon = create_wgs84_geojson_polygon_from_selection()
                preview = client.preview_area(self.polygon)
                logger.info("Preview area: %s", preview.tile_count)
                self.tile_count = preview.tile_count

                if preview.tile_count > 100:
                    QMessageBox.warning(
                        self,
                        "Wrong selection",
                        "The tile size can be between 0 and 100. Larger areas are not allowed. 2"
                    )
                    self.reject()
                    return

            except Exception as e:
                logger.exception("Error computing/plotting selection polygon: %s", e)
                QMessageBox.warning(
                    self,
                    "Error",
                    f"An error occurred while computing the selection polygon. Please try again. Message: {e}"
                )
                self.reject()
                return

            self.setWindowTitle(f"Run Simulation — {self.tile_count} tile{'s' if self.tile_count != 1 else ''} selected")
            logger.info("Dialog loaded, tile count: %d", self.tile_count)

        # The polygon is only known now — refresh the area-dependent status
        # labels that were initialised empty during widget setup.
        self._revalidate_trees()
        try:
            self._revalidate_ground_materials()
        except AttributeError:
            pass  # older .ui without the ground-material widgets

        self._init_ok = True

    def _on_use_catalog_toggled(self, checked):
        self.use_tree_catalog_type = bool(checked)
        self._revalidate_trees()

    def _revalidate_trees(self, *args):
        """Validate the selected tree layer over the area; update the status label.

        Counts tree points in the area and reports the breakdown: precise
        registry species, OSM-typed trees (rendered as archetypes by the
        backend), and untagged trees (broadleaf default). Never blocks a run —
        every tree renders. No-ops on an older .ui without the widgets.
        """
        try:
            label = self.tree_validation_label
            checkbox = self.use_catalog_checkbox
        except AttributeError:
            return
        current = self.analysis_type_dropdown.currentData()
        try:
            layer = selected_tree_layer(self.tree_layer_dropdown)
        except AttributeError:
            layer = None

        # The catalog fallback only makes sense when a tree layer is selected on
        # a vegetation-supporting analysis: show it only then, and never let it
        # be ticked without a layer. Reset it (signal-free) when hidden.
        supports = has_tree_support(current)
        show_catalog = supports and layer is not None
        checkbox.setVisible(show_catalog)
        checkbox.setEnabled(layer is not None)
        if not show_catalog and checkbox.isChecked():
            checkbox.blockSignals(True)
            checkbox.setChecked(False)
            checkbox.blockSignals(False)
            self.use_tree_catalog_type = False

        if layer is None or self.polygon is None or not supports:
            label.setText("")
            return
        try:
            result = validate_tree_layer(self.polygon, layer)
        except Exception as e:
            logger.warning("Tree validation failed: %s", e, exc_info=True)
            label.setText("")
            return

        # No tree points inside the selected area at all: the catalog fallback
        # has nothing to apply to, so disable it (unchecking signal-free), and
        # don't gate accept() — there is nothing to type.
        if result.detected == 0:
            checkbox.setEnabled(False)
            if checkbox.isChecked():
                checkbox.blockSignals(True)
                checkbox.setChecked(False)
                checkbox.blockSignals(False)
                self.use_tree_catalog_type = False
            label.setText(
                "No tree points detected in the selected area (nearby trees "
                "may still be included as shading/wind context)."
            )
            return

        if self.use_tree_catalog_type:
            label.setText(
                f"{result.detected} tree point(s) detected — using the tree catalog "
                f"tree type for all of them (overrides per-tree OSM types)."
            )
        else:
            # No blocking: every tree renders. Report the breakdown so the
            # user sees what will happen — precise registry species, OSM
            # archetypes, and the broadleaf default for untagged trees.
            parts = []
            if result.with_type_props:
                types_txt = ", ".join(
                    f"{count}× {name}"
                    for name, count in sorted(
                        result.type_counts.items(), key=lambda kv: (-kv[1], kv[0])
                    )
                )
                parts.append(f"{result.with_type_props} as a catalog species ({types_txt})")
            if result.with_archetype_signal:
                parts.append(
                    f"{result.with_archetype_signal} by their OSM type "
                    f"(genus/species/leaf_type) as an archetype"
                )
            if result.default_count:
                parts.append(f"{result.default_count} as the default broadleaf")
            if parts:
                detail = "; ".join(parts)
                label.setText(
                    f"{result.detected} tree point(s) detected — {detail}."
                )
            else:
                label.setText(f"{result.detected} tree point(s) detected.")

    # -- ground materials ---------------------------------------------------

    def _populate_ground_materials(self):
        """Fill the list with the project's ground-* layers (nothing ticked).

        One row PER LAYER — repeated fetches produce numbered layers
        (``ground-asphalt``, ``ground-asphalt-2``) that the user can tick
        individually. Each row shows ``material — layer name``; the
        (material, layer) pair travels in the item's UserRole data so
        display text can change freely.
        """
        from qgis.PyQt.QtCore import Qt
        from qgis.PyQt.QtWidgets import QListWidgetItem

        self._ground_layers = ground_material_layers()
        lst = self.ground_materials_list
        lst.blockSignals(True)
        lst.clear()
        for material in sorted(self._ground_layers):
            for layer in self._ground_layers[material]:
                item = QListWidgetItem(f"{material} — {layer.name()}")
                item.setData(Qt.ItemDataRole.UserRole, (material, layer))
                item.setFlags(item.flags() | Qt.ItemFlag.ItemIsUserCheckable)
                # Opt-in: ground materials are extra payload + server work,
                # so the dialog opens with nothing ticked.
                item.setCheckState(Qt.CheckState.Unchecked)
                lst.addItem(item)
        lst.blockSignals(False)
        self._revalidate_ground_materials()

    def _on_use_infrared_ground_toggled(self, checked):
        self.use_infrared_ground_materials = bool(checked)
        self._revalidate_ground_materials()

    def _on_ground_item_changed(self, changed_item):
        """Enforce one ticked layer per material, then revalidate.

        The simulation takes ONE FeatureCollection per material, so ticking
        e.g. a second asphalt layer silently unticks the first (radio-like,
        signal-free to avoid recursion).
        """
        from qgis.PyQt.QtCore import Qt

        if changed_item.checkState() == Qt.CheckState.Checked:
            data = changed_item.data(Qt.ItemDataRole.UserRole)
            if data:
                material = data[0]
                lst = self.ground_materials_list
                lst.blockSignals(True)
                for i in range(lst.count()):
                    item = lst.item(i)
                    if item is changed_item:
                        continue
                    other = item.data(Qt.ItemDataRole.UserRole)
                    if other and other[0] == material:
                        item.setCheckState(Qt.CheckState.Unchecked)
                lst.blockSignals(False)
        self._revalidate_ground_materials()

    def selected_ground_material_layers(self):
        """Return ``{material: [layers]}`` for the ticked list rows."""
        from qgis.PyQt.QtCore import Qt

        try:
            lst = self.ground_materials_list
        except AttributeError:
            return {}
        selected = {}
        for i in range(lst.count()):
            item = lst.item(i)
            if item.checkState() == Qt.CheckState.Checked:
                data = item.data(Qt.ItemDataRole.UserRole)
                if not data:
                    continue
                material, layer = data
                selected.setdefault(material, []).append(layer)
        return selected

    def _revalidate_ground_materials(self, *args):
        """Refresh ground-material widgets for the current analysis + area.

        Visibility: the whole section hides for analyses that ignore surface
        materials (wind, PWC, SVF). The auto-fetch checkbox is always shown
        for supported analyses (it needs no layers); the layer list only
        when ground-* layers exist, and disabled while auto-fetch is ticked.
        """
        try:
            label = self.ground_validation_label
            lst = self.ground_materials_list
            checkbox = self.use_infrared_ground_checkbox
        except AttributeError:
            return

        supported = has_ground_material_support(
            self.analysis_type_dropdown.currentData()
        )
        self.label_ground_materials.setVisible(supported)
        checkbox.setVisible(supported)
        lst.setVisible(supported and bool(self._ground_layers))
        label.setVisible(supported)
        if not supported:
            label.setText("")
            return

        lst.setEnabled(not self.use_infrared_ground_materials)
        if self.use_infrared_ground_materials:
            label.setText(
                "Infrared ground materials will be fetched automatically for "
                "the selected area at submit; ground-* layers are ignored."
            )
            return

        if not self._ground_layers:
            label.setText(
                "No ground-* layers in the project — fetch them with "
                "'Fetch ground materials', or tick the auto-fetch option."
            )
            return
        if self.polygon is None:
            label.setText("")
            return
        selected = self.selected_ground_material_layers()
        if not selected:
            # Nothing ticked (the default): silence — validation only ever
            # talks about layers the user opted into.
            label.setText("")
            return

        # Per-LAYER validation, tree-style but terser: only rows whose layer
        # has nothing inside the selected polygon are called out — layers
        # that do cover the area need no confirmation.
        missing = []
        total_rows = 0
        try:
            for material, material_layers in selected.items():
                for layer in material_layers:
                    total_rows += 1
                    found = validate_ground_material_layers(
                        self.polygon, {material: [layer]},
                    )
                    if not found:
                        missing.append(f"{material} — {layer.name()}")
        except Exception as e:
            logger.warning("Ground material validation failed: %s", e, exc_info=True)
            label.setText("")
            return
        if not missing:
            label.setText("")
        elif len(missing) == total_rows:
            subject = (
                "the ticked layer has" if total_rows == 1
                else "the ticked layers have"
            )
            label.setText(
                f"No ground material data found on the selected area — "
                f"{subject} no features inside your selection."
            )
        else:
            missing_txt = ", ".join(sorted(missing))
            label.setText(f"Not found on the selected area: {missing_txt}.")

    def on_analysis_changed(self, text):
        current = self.analysis_type_dropdown.currentData()

        # Refresh the tree-layer dropdown's enabled state — disabled when
        # the project has no tree-* layers OR when the new analysis type
        # is in the no-vegetation list (currently empty, all 8 supported).
        try:
            update_tree_layer_enabled(self.tree_layer_dropdown, current)
        except AttributeError:
            pass  # older .ui without the field

        # Re-run the tree + ground-material validation for the newly-selected
        # analysis (support may have changed) and refresh the status labels.
        self._revalidate_trees()
        try:
            self._revalidate_ground_materials()
        except AttributeError:
            pass  # older .ui without the ground-material widgets

        if self.bbox is not None and self.api_key and not self.weather_file_names:
            lon, lat = get_center_lon_lat_from_bbox(self.bbox, self.crs)
            try:
                self.weather_file_names = fetch_weather_file_names(lon, lat, 100, self.api_key)
            except InfraredAPIError as e:
                logger.error("API error fetching weather file names: %s", e, exc_info=True)
                QMessageBox.critical(self, e.title, e.detail)
                return
            except Exception as e:
                logger.error("Unexpected error fetching weather file names: %s", e, exc_info=True)
                QMessageBox.critical(self, "Error", f"Failed to fetch weather file names.\n\n{e}")
                return

        # Switch stacked pages by widget name — robust against page reordering
        _page_map = {
            AnalysisType.WIND_SPEED: self.page_wind_speed,
            AnalysisType.PEDESTRIAN_WIND_COMFORT: self.page_pedestrian_wind_comfort,
            AnalysisType.THERMAL_COMFORT_INDEX: self.page_thermal_comfort_index,
            AnalysisType.THERMAL_COMFORT_STATISTICS: self.page_thermal_comfort_statistics,
            AnalysisType.SOLAR_RADIATION: self.page_solar_radiation,
            AnalysisType.DAYLIGHT_AVAILABILITY: self.page_daylight_availability,
            AnalysisType.DIRECT_SUN_HOURS: self.page_direct_sun_hours,
            AnalysisType.SKY_VIEW_FACTORS: self.page_sky_view_factors,
        }
        try:
            page = _page_map.get(current)
            if page is not None:
                self.content_stack.setCurrentWidget(page)
        except AttributeError:
            # Fallback for older UI without stacked widget
            try:
                self.group_wind_speed.setVisible(current == AnalysisType.WIND_SPEED)
                self.group_pedestrian_wind_comfort.setVisible(current == AnalysisType.PEDESTRIAN_WIND_COMFORT)
                self.group_thermal_comfort.setVisible(current == AnalysisType.THERMAL_COMFORT_INDEX)
                self.group_thermal_comfort_statistics.setVisible(current == AnalysisType.THERMAL_COMFORT_STATISTICS)
                self.group_solar_radiation.setVisible(current == AnalysisType.SOLAR_RADIATION)
                self.group_daylight_availability.setVisible(current == AnalysisType.DAYLIGHT_AVAILABILITY)
                self.group_direct_sun_hours.setVisible(current == AnalysisType.DIRECT_SUN_HOURS)
                self.group_sky_view_factors.setVisible(current == AnalysisType.SKY_VIEW_FACTORS)
                # self.group_shadow_mask.setVisible(current == AnalysisType.SHADOW_MASK)
            except AttributeError as e:
                logger.error("Failed to update group visibility: %s", str(e), exc_info=True)

        if current == AnalysisType.PEDESTRIAN_WIND_COMFORT:
            try:
                self.weather_file_input_pwc.setEditable(True)
                self.weather_file_input_pwc.clear()

                for w in self.weather_file_names:
                    self.weather_file_input_pwc.addItem(w, w)

                self.pwc_type_dropdown.clear()
                for s in PedestrianWindComfortType:
                    self.pwc_type_dropdown.addItem(str(s), s)

                self.season_dropdown_pwc.clear()
                for season in SeasonalTimeFrameConfig:
                    self.season_dropdown_pwc.addItem(season.value, season)

                self.hours_dropdown_pwc.clear()
                for hours in DailyTimeFrameConfig:
                    self.hours_dropdown_pwc.addItem(hours.value, hours)
            except Exception as e:
                logger.error("Failed to populate PWC dialog elements: %s", str(e), exc_info=True)
        if current == AnalysisType.THERMAL_COMFORT_INDEX:
            try:
                self.weather_file_input_tci.setEditable(True)
                self.weather_file_input_tci.clear()

                for w in self.weather_file_names:
                    self.weather_file_input_tci.addItem(w, w)

                self.legend_min_input_tci.setEnabled(False)
                self.legend_max_input_tci.setEnabled(False)
                self.legend_min_enable_tci.toggled.connect(self.legend_min_input_tci.setEnabled)
                self.legend_max_enable_tci.toggled.connect(self.legend_max_input_tci.setEnabled)

                self.month_dropdown_tci.clear()
                for month in MonthConfig:
                    self.month_dropdown_tci.addItem(month.value, month)

                self.hours_dropdown_tci.clear()
                for hours in DailyTimeFrameConfigUTCI:
                    self.hours_dropdown_tci.addItem(hours.value, hours)
            except AttributeError as e:
                logger.error("Failed to populate TCI dialog elements: %s", str(e), exc_info=True)
        if current == AnalysisType.THERMAL_COMFORT_STATISTICS:
            try:
                self.weather_file_input_tcs.setEditable(True)
                self.weather_file_input_tcs.clear()

                for w in self.weather_file_names:
                    self.weather_file_input_tcs.addItem(w, w)

                self.season_dropdown_tcs.clear()
                for season in SeasonalTimeFrameConfig:
                    self.season_dropdown_tcs.addItem(season.value, season)

                self.hours_dropdown_tcs.clear()
                for hours in DailyTimeFrameConfigUTCI:
                    self.hours_dropdown_tcs.addItem(hours.value, hours)

                self.tcs_type_dropdown.clear()
                for tcs_type in ThermalComfortStatisticsType:
                    self.tcs_type_dropdown.addItem(tcs_type.value, tcs_type)
            except Exception as e:
                logger.error("Failed to populate TCS dialog elements: %s", str(e), exc_info=True)
        if current == AnalysisType.SOLAR_RADIATION:
            try:
                self.weather_file_input_sr.setEditable(True)
                self.weather_file_input_sr.clear()

                for w in self.weather_file_names:
                    self.weather_file_input_sr.addItem(w, w)

                self.month_dropdown_sr.clear()
                for month in MonthConfig:
                    self.month_dropdown_sr.addItem(month.value, month)

                self.hours_dropdown_sr.clear()
                for hours in DailyTimeFrameConfig:
                    self.hours_dropdown_sr.addItem(hours.value, hours)
            except Exception as e:
                logger.error("Failed to populate solar radiation dialog elements: %s", str(e), exc_info=True)
        if current == AnalysisType.DAYLIGHT_AVAILABILITY:
            try:
                self.month_dropdown_da.clear()
                for month in MonthConfig:
                    self.month_dropdown_da.addItem(month.value, month)

                self.hours_dropdown_da.clear()
                for hours in DailyTimeFrameConfig:
                    self.hours_dropdown_da.addItem(hours.value, hours)
            except Exception as e:
                logger.error("Failed to populate daylight availability dialog elements: %s", str(e), exc_info=True)
        if current == AnalysisType.DIRECT_SUN_HOURS:
            try:
                self.month_dropdown_dsh.clear()
                for month in MonthConfig:
                    self.month_dropdown_dsh.addItem(month.value, month)

                self.hours_dropdown_dsh.clear()
                for hours in DailyTimeFrameConfig:
                    self.hours_dropdown_dsh.addItem(hours.value, hours)
            except Exception as e:
                logger.error("Failed to populate direct sun hours dialog elements: %s", str(e), exc_info=True)

    def _setup_epw_uploads(self):
        """Add an 'Upload EPW…' control to each weather-based analysis page.

        Lets the user run PWC / TCI / TCS / Solar Radiation against a local
        ``.epw`` file instead of an infrared.city weather station — mirrors the
        ArcGIS plugin's upload toggle. Picking a file disables the station
        combo and flips the button to 'Remove uploaded file'.
        """
        specs = [
            (getattr(self, "page_pedestrian_wind_comfort", None),
             getattr(self, "weather_file_input_pwc", None),
             AnalysisType.PEDESTRIAN_WIND_COMFORT),
            (getattr(self, "page_thermal_comfort_index", None),
             getattr(self, "weather_file_input_tci", None),
             AnalysisType.THERMAL_COMFORT_INDEX),
            (getattr(self, "page_thermal_comfort_statistics", None),
             getattr(self, "weather_file_input_tcs", None),
             AnalysisType.THERMAL_COMFORT_STATISTICS),
            (getattr(self, "page_solar_radiation", None),
             getattr(self, "weather_file_input_sr", None),
             AnalysisType.SOLAR_RADIATION),
        ]
        for page, combo, at in specs:
            if page is None or combo is None:
                continue
            try:
                self._wire_epw_upload(page, combo, at)
            except Exception as e:
                logger.warning("Could not add EPW upload for %s: %s", at, e)

    def _wire_epw_upload(self, page, combo, analysis_type):
        """Build + wire one page's EPW upload toggle (button + status label)."""
        from qgis.PyQt.QtWidgets import (
            QFileDialog,
            QHBoxLayout,
            QLabel,
            QPushButton,
            QWidget,
        )

        row = QWidget(page)
        h = QHBoxLayout(row)
        h.setContentsMargins(0, 0, 0, 0)
        h.setSpacing(6)
        btn = QPushButton("Upload EPW…", row)
        btn.setCheckable(True)
        status = QLabel("", row)
        status.setStyleSheet("color: #555;")
        h.addWidget(btn)
        h.addWidget(status)
        h.addStretch()

        page_layout = page.layout()
        if page_layout is not None:
            page_layout.addWidget(row)

        def on_toggled(checked):
            if checked:
                path, _ = QFileDialog.getOpenFileName(
                    self, "Select EPW weather file", "",
                    "EnergyPlus Weather (*.epw);;All files (*)",
                )
                if not path:
                    btn.setChecked(False)
                    return
                try:
                    from .services.epw_parser import validate_file
                    validate_file(path)
                except Exception as e:
                    QMessageBox.warning(
                        self, "Invalid EPW", f"Not a usable EPW file:\n\n{e}",
                    )
                    btn.setChecked(False)
                    return
                self._epw_paths[analysis_type] = path
                combo.setEnabled(False)
                status.setText(f"Using uploaded: {os.path.basename(path)}")
                btn.setText("Remove uploaded file")
                # Log only the basename — the full path leaks the user's home
                # dir / username (PII) into the plugin log.
                logger.info("EPW uploaded for %s: %s", analysis_type, os.path.basename(path))
            else:
                self._epw_paths.pop(analysis_type, None)
                combo.setEnabled(True)
                status.setText("")
                btn.setText("Upload EPW…")

        btn.toggled.connect(on_toggled)

    def accept(self):
        try:
            logger.info("\n ✨ ✨ ✨ ✨ ✨ ✨ ✨ MULTIPLE SIMULATION RUN START ✨ ✨ ✨ ✨ ✨ ✨ ✨ ")

            if not self.api_key:
                QMessageBox.warning(
                    self, "Missing API Key",
                    "No API key found. Please save your API key first via the 'Save API Key' menu."
                )
                return

            if self.polygon is None:
                logger.warning("No valid selection — cannot fetch buildings")
                QMessageBox.warning(
                    self, "No selection",
                    "Select one or more features before running the simulation."
                )
                return
            logger.info("Polygon (WGS84) ring length: %d", len(self.polygon["coordinates"][0]))

            # Refresh the tree breakdown label for the confirmed polygon. No
            # gate: any OSM tree layer is submittable — trees that don't match
            # a precise registry species are resolved to an archetype by the
            # backend (untagged → broadleaf), so nothing is ever un-typeable.
            self._revalidate_trees()

            # Collect buildings from the active QGIS layer instead of the
            # SDK's Mapbox fetch — same return type (AreaBuildings, in
            # polygon-bbox-SW frame), so it plugs straight into
            # run_area_and_wait(buildings=area.buildings) below.
            area = collect_qgis_area_buildings(self.polygon)
            logger.info("Total buildings (from QGIS): %s", area.total_buildings)

            # Async path: submit jobs, hand off to a QTimer-driven poller,
            # then close the dialog immediately. The poller is parented to
            # iface.mainWindow() so it survives this dialog being destroyed
            # and renders the result on the canvas when polling completes.
            #
            # Single-tile mode submits ONE job via analyses.execute (≈10
            # tokens); area mode fans the polygon out across the tiler.
            if self.is_single_tile:
                poller = run_sdk_single_tile_async(self, self.polygon, area)
            else:
                poller = run_sdk_area_async(self, self.polygon, area)
            if poller is None:
                # Payload validation failed; build_sdk_payload already
                # showed a QMessageBox. Keep the dialog open.
                return

            # Simulation submitted — now consume the one-shot single-tile
            # selection so the next dialog open falls back to area mode.
            # (We only peek() on open, so closing without running keeps it.)
            if self.is_single_tile:
                single_tile_selection.clear()

            super().accept()

        except InfraredAPIError as e:
            logger.error("API error in accept(): %s", e, exc_info=True)
            QMessageBox.critical(self, e.title, e.detail)
        except Exception as e:
            logger.error("Unhandled exception in accept(): %s", e, exc_info=True)
            msg = str(e)
            short_msg = msg if len(msg) < 200 else msg[:200] + "…"
            QMessageBox.critical(
                self,
                "Error",
                "An error occurred during the simulation.\n"
                f"Details: {short_msg}\n\nCheck the plugin log for more information."
            )
