# -*- coding: utf-8 -*-
"""
/***************************************************************************
 InfraredCityDialog
                                 A QGIS plugin
 This is a plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-13
        git sha              : $Format:%H$
        copyright            : (C) 2025 by infrared.city
        email                : connectors@infrared.city
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtWidgets import QLineEdit, QMessageBox
from .infrared_logger import logger
from .visualization.display import display_geojson
from .services.fetch import fetch_geometry_from_osm, fetch_weather_file_names
from .services.secret_manager import get_api_key, set_api_key
from .exceptions import InfraredAPIError
# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'infrared_city_fetch_weather_file_names_dialog.ui'))


class InfraredCityFetchWeatherFileNamesDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(InfraredCityFetchWeatherFileNamesDialog, self).__init__(parent)

        self.setupUi(self)
        logger.info("Dialog loaded")

        self.button_box.accepted.connect(self.accept)
        self.button_box.rejected.connect(self.reject)
        self.api_key = None

        # Mask the API key input — defends against shoulder surfing and
        # accidental screen recording. The dialog used to log the key
        # value too; that's been removed.
        try:
            self.api_key_input.setEchoMode(QLineEdit.Password)
        except Exception:
            pass

        # Pre-fill from QSettings (or INFRARED_API_KEY env var) so the
        # user doesn't have to re-paste their key every time. Storage
        # moved from settings/user.json to QSettings — the legacy file is
        # no longer consulted.
        try:
            existing = get_api_key()
            if existing:
                self.api_key_input.setText(existing)
                self.api_key = existing
                logger.info("API key pre-filled from store")
        except Exception as e:
            logger.warning("Could not read API key: %s", e)



    def accept(self):
        """Run fetch when OK is pressed."""
        longitude = self.longitude_input.text().strip()
        latitude = self.latitude_input.text().strip()
        radius = self.radius_input.text().strip()
        
        # --- Validation ---
        if not longitude or not latitude or not radius:
            logger.warning("Missing input")
            QMessageBox.warning(self, "Missing Input", "Please fill in all fields!")
            return

        try:
            lon = float(longitude)
            lat = float(latitude)
            radius = float(radius)
        except ValueError:
            logger.error("Invalid input")
            QMessageBox.warning(self, "Invalid Input", "Coordinates and bbox must be numbers.")
            return
        
        self.api_key = self.api_key_input.text().strip()
        if not self.api_key:
            logger.warning("API key is empty. Please fill in the API key.")
            QMessageBox.warning(self, "Missing API Key", "Please fill in the API key.")
            return

        # Persist to QSettings (replacing the legacy user.json file).
        # set_api_key logs only "saved" — never the secret value itself.
        if not set_api_key(self.api_key):
            logger.error("Failed to save API key")

        # --- Fetch ---
        try:
            locations = fetch_weather_file_names(lon, lat, radius, self.api_key)

            #save_locations_to_file(locations)

        except InfraredAPIError as e:
            logger.error(f"API error fetching weather file names: {e}", exc_info=True)
            QMessageBox.critical(self, e.title, e.detail)
            return
        except Exception as e:
            logger.error(f"Failed to fetch weather file names: {e}", exc_info=True)
            QMessageBox.critical(self, "Error", f"Failed to fetch weather file names.\n\n{e}")
            return

        super().accept()