# -*- coding: utf-8 -*-
"""
/***************************************************************************
 InfraredCityDialog
                                 A QGIS plugin
 This is a plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-13
        git sha              : $Format:%H$
        copyright            : (C) 2025 by infrared.city
        email                : connectors@infrared.city
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.core import Qgis
from qgis.PyQt import QtWidgets, uic
from qgis.PyQt.QtWidgets import QMessageBox
from qgis.utils import iface

from .client import (
    get_daylight_availability_payload,
    get_direct_sun_hours_payload,
    get_pwc_payload,
    get_solar_radiation_payload,
    get_tcs_payload,
    get_utci_payload,
    get_windspeed_payload,
    load_dotbim,
    process_run_analysis,
)
from .exceptions import InfraredAPIError
from .infrared_logger import logger
from .models.analysis import (
    AnalysisType,
    GeometryTypes,
    PedestrianWindComfortType,
    ThermalComfortStatisticsType,
)
from .models.timeframes_parser import (
    DailyTimeFrameConfig,
    DailyTimeFrameConfigUTCI,
    MonthConfig,
    SeasonalTimeFrameConfig,
    makeTimeFrameObj,
    makeTimeFrameObjWithMonth,
)
from .services.epw_query import Query_Type, query_infrared_epw
from .services.fetch import fetch_weather_file_names
from .services.geometry import (
    collect_geometries,
    create_wgs84_geojson_polygon_from_selection,
    get_center_from_bbox,
    get_center_lon_lat_from_bbox,
    get_selected_bbox,
    get_selected_crs,
)
from .services.qgis_area_buildings import collect_qgis_area_buildings
from .services.sdk_runner import run_sdk_area_async
from .services.secret_manager import get_api_key
from .services.tree_layer_picker import (
    has_tree_support,
    populate_tree_layer_dropdown,
    selected_tree_layer,
    update_tree_layer_enabled,
)
from .visualization.display import add_geojson_then_raster, deselect_all

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'infrared_city_run_simulation_dialog.ui'))


class InfraredCityRunSimulationDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None, dotbim_path=None, geojson_path=None ,bbox=None,crs=None):
        super().__init__(parent)
        self.setupUi(self)

        self._init_ok = False

        self.dotbim_path = dotbim_path
        self.geojson_path = geojson_path
        self.geotiff_path = None
        self.bbox = bbox
        self.crs = crs
        self.colors = None
        self.weather_file_names = []
        self.analysis_type_dropdown.clear()
        for t in AnalysisType:
            self.analysis_type_dropdown.addItem(str(t), t)
        self.analysis_type_dropdown.currentTextChanged.connect(self.on_analysis_changed)
        self.analysis_type = None
        self.api_key = None
        self.selected_legend_min = None
        self.selected_legend_max = None

        self.button_box.accepted.connect(self.accept)
        self.button_box.rejected.connect(self.reject)

        # Populate the "Tree layer" dropdown from the current project; the
        # subsequent on_analysis_changed call will grey it out if either
        # there are no candidate layers or the analysis doesn't support
        # vegetation.
        try:
            populate_tree_layer_dropdown(self.tree_layer_dropdown)
        except AttributeError:
            logger.warning("tree_layer_dropdown not present in dialog — skipping")

        if self.crs is not None:
            iface.messageBar().pushMessage(
                "InfraredCity",
                f"Layer CRS is the following: {self.crs}",
                level=Qgis.Info,
                duration=7
            )

        if self.analysis_type_dropdown.count() > 0:
            self.analysis_type_dropdown.setCurrentIndex(0)
            self.on_analysis_changed(self.analysis_type_dropdown.currentText())


        # Load API key from QSettings (or INFRARED_API_KEY env var) via the
        # secret_manager. The legacy settings/user.json file is no longer
        # consulted — the Save API Key dialog writes only to QSettings.
        try:
            self.api_key = get_api_key()
            if self.api_key:
                logger.info("API key loaded")
        except Exception as e:
            logger.warning("Could not read API key: %s", e)

        if not self.api_key:
            QMessageBox.warning(
                self,
                "Missing API Key",
                "No API key found. Please save your API key first via the 'Save API Key' menu."
            )
            self.reject()
            return



        logger.info("Dialog loaded")
        logger.info("Dotbim path: %s", self.dotbim_path)
        logger.info("Geojson path: %s", self.geojson_path)
        logger.info("Bbox: %s", self.bbox)
        logger.info("CRS: %s", self.crs)

        self._init_ok = True



    def on_analysis_changed(self, text):
        current = self.analysis_type_dropdown.currentData()

        # Refresh the tree-layer dropdown's enabled state — disabled when
        # the project has no tree-* layers OR when the new analysis type
        # is in the no-vegetation list (currently empty, all 8 supported).
        try:
            update_tree_layer_enabled(self.tree_layer_dropdown, current)
        except AttributeError:
            pass  # older .ui without the field

        # Get weather file names
        if self.bbox is not None and self.api_key and not self.weather_file_names:
            lon, lat = get_center_lon_lat_from_bbox(self.bbox, self.crs)
            try:
                self.weather_file_names = fetch_weather_file_names(lon, lat, 100, self.api_key)
            except InfraredAPIError as e:
                logger.error("API error fetching weather file names: %s", e, exc_info=True)
                QMessageBox.critical(self, e.title, e.detail)
                return
            except Exception as e:
                logger.error("Unexpected error fetching weather file names: %s", e, exc_info=True)
                QMessageBox.critical(self, "Error", f"Failed to fetch weather file names.\n\n{e}")
                return

        # Switch stacked pages by widget name — robust against page reordering
        _page_map = {
            AnalysisType.WIND_SPEED: self.page_wind_speed,
            AnalysisType.PEDESTRIAN_WIND_COMFORT: self.page_pedestrian_wind_comfort,
            AnalysisType.THERMAL_COMFORT_INDEX: self.page_thermal_comfort_index,
            AnalysisType.THERMAL_COMFORT_STATISTICS: self.page_thermal_comfort_statistics,
            AnalysisType.SOLAR_RADIATION: self.page_solar_radiation,
            AnalysisType.DAYLIGHT_AVAILABILITY: self.page_daylight_availability,
            AnalysisType.DIRECT_SUN_HOURS: self.page_direct_sun_hours,
            AnalysisType.SKY_VIEW_FACTORS: self.page_sky_view_factors,
        }
        try:
            page = _page_map.get(current)
            if page is not None:
                self.content_stack.setCurrentWidget(page)
        except AttributeError:
            # Fallback for older UI without stacked widget
            try:
                self.group_wind_speed.setVisible(current == AnalysisType.WIND_SPEED)
                self.group_pedestrian_wind_comfort.setVisible(current == AnalysisType.PEDESTRIAN_WIND_COMFORT)
                self.group_thermal_comfort.setVisible(current == AnalysisType.THERMAL_COMFORT_INDEX)
                self.group_thermal_comfort_statistics.setVisible(current == AnalysisType.THERMAL_COMFORT_STATISTICS)
                self.group_solar_radiation.setVisible(current == AnalysisType.SOLAR_RADIATION)
                self.group_daylight_availability.setVisible(current == AnalysisType.DAYLIGHT_AVAILABILITY)
                self.group_direct_sun_hours.setVisible(current == AnalysisType.DIRECT_SUN_HOURS)
                self.group_sky_view_factors.setVisible(current == AnalysisType.SKY_VIEW_FACTORS)
                #self.group_shadow_mask.setVisible(current == AnalysisType.SHADOW_MASK)
            except AttributeError as e:
                logger.error("Failed to update group visibility: %s", str(e), exc_info=True)

        if current == AnalysisType.PEDESTRIAN_WIND_COMFORT:
            try:
                self.weather_file_input_pwc.setEditable(True)
                self.weather_file_input_pwc.clear()

                for w in self.weather_file_names:
                    self.weather_file_input_pwc.addItem(w, w)

                self.pwc_type_dropdown.clear()
                for s in PedestrianWindComfortType:
                    self.pwc_type_dropdown.addItem(str(s), s)

                self.season_dropdown_pwc.clear()
                for season in SeasonalTimeFrameConfig:
                    self.season_dropdown_pwc.addItem(season.value, season)

                self.hours_dropdown_pwc.clear()
                for hours in DailyTimeFrameConfig:
                    self.hours_dropdown_pwc.addItem(hours.value, hours)
            except Exception as e:
                logger.error("Failed to populate PWC dialog elements: %s", str(e), exc_info=True)

        if current == AnalysisType.THERMAL_COMFORT_INDEX:
            try:
                self.weather_file_input_tci.setEditable(True)
                self.weather_file_input_tci.clear()

                for w in self.weather_file_names:
                    self.weather_file_input_tci.addItem(w, w)

                self.legend_min_input_tci.setEnabled(False)
                self.legend_max_input_tci.setEnabled(False)
                self.legend_min_enable_tci.toggled.connect(self.legend_min_input_tci.setEnabled)
                self.legend_max_enable_tci.toggled.connect(self.legend_max_input_tci.setEnabled)

                self.month_dropdown_tci.clear()
                for month in MonthConfig:
                    self.month_dropdown_tci.addItem(month.value, month)

                self.hours_dropdown_tci.clear()
                for hours in DailyTimeFrameConfigUTCI:
                    self.hours_dropdown_tci.addItem(hours.value, hours)
            except AttributeError as e:
                logger.error("Failed to populate TCI dialog elements: %s", str(e), exc_info=True)

        if current == AnalysisType.THERMAL_COMFORT_STATISTICS:
            try:
                self.weather_file_input_tcs.setEditable(True)
                self.weather_file_input_tcs.clear()

                for w in self.weather_file_names:
                    self.weather_file_input_tcs.addItem(w, w)

                self.season_dropdown_tcs.clear()
                for season in SeasonalTimeFrameConfig:
                    self.season_dropdown_tcs.addItem(season.value, season)

                self.hours_dropdown_tcs.clear()
                for hours in DailyTimeFrameConfigUTCI:
                    self.hours_dropdown_tcs.addItem(hours.value, hours)

                self.tcs_type_dropdown.clear()
                for tcs_type in ThermalComfortStatisticsType:
                    self.tcs_type_dropdown.addItem(tcs_type.value, tcs_type)
            except Exception as e:
                logger.error("Failed to populate TCS dialog elements: %s", str(e), exc_info=True)

        if current == AnalysisType.SOLAR_RADIATION:
            try:
                self.weather_file_input_sr.setEditable(True)
                self.weather_file_input_sr.clear()

                for w in self.weather_file_names:
                    self.weather_file_input_sr.addItem(w, w)

                self.month_dropdown_sr.clear()
                for month in MonthConfig:
                    self.month_dropdown_sr.addItem(month.value, month)

                self.hours_dropdown_sr.clear()
                for hours in DailyTimeFrameConfig:
                    self.hours_dropdown_sr.addItem(hours.value, hours)
            except Exception as e:
                logger.error("Failed to populate solar radiation dialog elements: %s", str(e), exc_info=True)

        if current == AnalysisType.DAYLIGHT_AVAILABILITY:
            try:
                self.month_dropdown_da.clear()
                for month in MonthConfig:
                    self.month_dropdown_da.addItem(month.value, month)

                self.hours_dropdown_da.clear()
                for hours in DailyTimeFrameConfig:
                    self.hours_dropdown_da.addItem(hours.value, hours)
            except Exception as e:
                logger.error("Failed to populate daylight availability dialog elements: %s", str(e), exc_info=True)

        if current == AnalysisType.DIRECT_SUN_HOURS:
            try:
                self.month_dropdown_dsh.clear()
                for month in MonthConfig:
                    self.month_dropdown_dsh.addItem(month.value, month)

                self.hours_dropdown_dsh.clear()
                for hours in DailyTimeFrameConfig:
                    self.hours_dropdown_dsh.addItem(hours.value, hours)
            except Exception as e:
                logger.error("Failed to populate direct sun hours dialog elements: %s", str(e), exc_info=True)

        # if current == AnalysisType.SHADOW_MASK:
        #     try:
        #         self.datetime_input_sm.setDateTime(QDateTime.currentDateTime())
        #     except Exception as e:
        #         logger.error("Failed to populate shadow mask dialog elements: %s", str(e), exc_info=True)

    def accept(self):

        try:
            logger.info("\n ✨ ✨ ✨ ✨ ✨ ✨ ✨ SIMULATION RUN START ✨ ✨ ✨ ✨ ✨ ✨ ✨")

            logger.info(f"Accept called. Sender: {self.sender()}")
            tree_dotbim = None
            criteria = None

            # ----------------------------------------------------------
            # SDK path (default for fresh dialog opens — same flow as the
            # run-multiple dialog). The legacy per-tile path below is
            # only reached when a pre-fetched ``dotbim_path`` was passed
            # by the legacy "Fetch Geometry" two-step workflow.
            # ----------------------------------------------------------
            if self.dotbim_path is None:
                if not self.api_key:
                    QMessageBox.warning(
                        self, "Missing API Key",
                        "No API key found. Please save your API key first via the 'Save API Key' menu.",
                    )
                    return

                polygon = create_wgs84_geojson_polygon_from_selection()
                if polygon is None:
                    QMessageBox.warning(
                        self, "No selection",
                        "Select one or more features before running the simulation.",
                    )
                    return

                # Populate self.bbox / self.crs from the active selection
                # so build_sdk_payload's get_center_lon_lat_from_bbox calls
                # (used by solar / UTCI / TCS payloads) have something to
                # work with.
                try:
                    w, s, e, n = get_selected_bbox()
                    self.bbox = [w, s, e, n]
                    self.crs = get_selected_crs()
                except Exception as e:
                    logger.warning("Could not derive bbox/crs from selection: %s", e)

                area = collect_qgis_area_buildings(polygon)
                logger.info("Total buildings (from QGIS): %s", area.total_buildings)

                poller = run_sdk_area_async(self, polygon, area)
                if poller is None:
                    # Payload validation failed; build_sdk_payload already
                    # showed a QMessageBox. Keep the dialog open.
                    return
                super().accept()
                return

            # ----------------------------------------------------------
            # Legacy path: caller (Fetch Geometry workflow) provided a
            # pre-fetched ``dotbim_path``. Falls through into the original
            # per-tile process_run_analysis flow below.
            # ----------------------------------------------------------
            if self.bbox is not None and self.crs is not None:
                center_x, center_y = get_center_from_bbox(self.bbox)
                logger.info("Bbox: %s, CRS: %s", self.bbox, self.crs)
                logger.info("Center center_x/center_y: %s, %s", center_x, center_y)

                buildings = None
                if self.dotbim_path is None:
                    buildings = collect_geometries(center_x, center_y, 1, geometry_type=GeometryTypes.BUILDINGS)

                # Trees: same gating as the run-multiple dialog — only
                # collect vegetation when the user has explicitly picked
                # a layer in the "Tree layer" combo *and* the current
                # analysis supports vegetation. "(none)" → trees=None →
                # downstream skips the dotbim load entirely.
                # NOTE: self.analysis_type is only set later in accept()
                # (after the geometry block), so read the analysis type
                # directly from the dropdown here.
                current_analysis_type = self.analysis_type_dropdown.currentData()
                trees = None
                tree_layer = None
                try:
                    tree_layer = selected_tree_layer(self.tree_layer_dropdown)
                except AttributeError:
                    pass  # older .ui without the combo
                if tree_layer is not None and has_tree_support(current_analysis_type):
                    trees = collect_geometries(
                        center_x, center_y, 1,
                        geometry_type=GeometryTypes.TREES,
                        layer_override=tree_layer,
                    )

                if buildings and not self.dotbim_path:
                    geojson_path, dotbim_path, bbox_512, crs_authid, bbox_256 = buildings
                    logger.info("Buildings found for the selection.")

                    self.dotbim_path = dotbim_path
                    self.bbox = bbox_512
                    self.crs = crs_authid
                    logger.info("Dotbim path: %s", self.dotbim_path)

                if trees:
                    geojson_path_trees, dotbim_path_trees, bbox_512_trees, crs_authid_trees, bbox_256_trees = trees
                    logger.info("Trees found the selection.")

                    tree_dotbim =  load_dotbim(dotbim_path_trees)
                    logger.info("Tree dotbim was loaded")

            else:
                logger.warning("No geometry fetched. Please fetch geometry first.")
                QMessageBox.warning(self, "Missing Geometry", "Please fetch or select geometry first.")
                return

            if not self.dotbim_path or not os.path.exists(self.dotbim_path):
                logger.warning("No geometry fetched. Please fetch geometry first.")
                QMessageBox.warning(self, "Missing Geometry", "Please fetch or select geometry first.")
                return

            self.analysis_type = self.analysis_type_dropdown.currentData()
            self.sub_analysis_type = None


            if not self.api_key:
                logger.warning("API key is empty.")
                QMessageBox.warning(
                    self,
                    "Missing API Key",
                    "No API key found. Please save your API key first via the 'Save API Key' menu."
                )
                return


            if self.analysis_type == AnalysisType.WIND_SPEED:
                # Validation
                wind_speed = self.wind_speed_input.value()
                wind_direction = self.wind_direction_input.value()

                if  (wind_speed <= 0 or wind_direction < 0 or wind_direction > 360):
                    logger.warning("Invalid parameters. Please check the input values.")
                    QMessageBox.warning(self, "Invalid Parameters", "Wind speed must be >0 and direction between 0-360°.")
                    return

                # Collect payload
                payload = get_windspeed_payload(wind_direction, wind_speed)

            elif self.analysis_type == AnalysisType.PEDESTRIAN_WIND_COMFORT:
                # Validation
                try:

                    pwc_type = self.pwc_type_dropdown.currentData()
                    criteria = pwc_type
                    self.sub_analysis_type = pwc_type
                    selected_season = self.season_dropdown_pwc.currentData()
                    selected_hours = self.hours_dropdown_pwc.currentData()
                    weather_file = self.weather_file_input_pwc.currentText().strip()
                    logger.info(f"Weather file: {weather_file}")

                except AttributeError:
                    logger.warning("Missing input")
                    QMessageBox.warning(self, "Missing Input", "Please fill in all fields!")
                    return

                time_frame = makeTimeFrameObj(isNorthHem=True, season=selected_season.value, hourly=selected_hours.value)
                logger.info(f"Weather file: {weather_file}")
                logger.info(f"Time frame: {time_frame}")
                wind_data = query_infrared_epw(
                        file_name=weather_file,
                        type=Query_Type.WIND,
                        time_frame=time_frame,
                        api_key=self.api_key
                    )
                logger.info("Wind data: windSpeed length=%d, windDirection length=%d",
                    len(wind_data["windSpeed"]), len(wind_data["windDirection"]))

                center_lon, center_lat = get_center_lon_lat_from_bbox(self.bbox,self.crs)

                payload = get_pwc_payload(wind_data,self.sub_analysis_type.value)

            elif self.analysis_type == AnalysisType.THERMAL_COMFORT_INDEX:
                # Validation
                try:
                    selected_month = self.month_dropdown_tci.currentData()
                    selected_hours = self.hours_dropdown_tci.currentData()
                    if self.legend_min_enable_tci.isChecked():
                        self.selected_legend_min = self.legend_min_input_tci.value()
                    if self.legend_max_enable_tci.isChecked():
                        self.selected_legend_max = self.legend_max_input_tci.value()
                    weather_file = self.weather_file_input_tci.currentText().strip()
                    logger.info(f"Weather file: {weather_file}")

                except AttributeError:
                    logger.warning("Missing input, Selected season and hours are required.")
                    QMessageBox.warning(self, "Missing Input", "Selected season and hours are required.")
                    return

                time_frame = makeTimeFrameObjWithMonth(month=selected_month.number, hourly=selected_hours.value)

                weather_data = query_infrared_epw(
                        file_name=weather_file,
                        type=Query_Type.UTCI,
                        time_frame=time_frame,
                        api_key=self.api_key
                    )
                center_lon, center_lat = get_center_lon_lat_from_bbox(self.bbox,self.crs)
                payload = get_utci_payload(weather_data,center_lon, center_lat, time_frame)

            elif self.analysis_type == AnalysisType.THERMAL_COMFORT_STATISTICS:
                # Validation
                try:
                    selected_season = self.season_dropdown_tcs.currentData()
                    selected_hours = self.hours_dropdown_tcs.currentData()
                    selected_tcs_type = self.tcs_type_dropdown.currentData()
                    self.sub_analysis_type = selected_tcs_type

                    weather_file = self.weather_file_input_tcs.currentText().strip()
                    logger.info(f"Weather file: {weather_file}")

                except AttributeError:
                    logger.warning("Missing input. TCS type is required.")
                    QMessageBox.warning(self, "Missing Input", "TCS type is required.")
                    return

                time_frame = makeTimeFrameObj(isNorthHem=True,season=selected_season.value,hourly=selected_hours.value,analysis_type=self.analysis_type)

                weather_data = query_infrared_epw(
                        file_name=weather_file,
                        type=Query_Type.UTCI,
                        time_frame=time_frame,
                        api_key=self.api_key
                    )
                center_lon, center_lat = get_center_lon_lat_from_bbox(self.bbox,self.crs)
                payload = get_tcs_payload(weather_data,center_lon,center_lat,time_frame,selected_tcs_type.value)

            elif self.analysis_type == AnalysisType.SOLAR_RADIATION:
                # Validation
                try:
                    selected_month = self.month_dropdown_sr.currentData()
                    selected_hours = self.hours_dropdown_sr.currentData()
                    weather_file = self.weather_file_input_sr.currentText().strip()
                    logger.info(f"Weather file: {weather_file}")
                except AttributeError:
                    logger.warning("Missing input, Selected month and hours are required.")
                    QMessageBox.warning(self, "Missing Input", "Selected month and hours are required.")
                    return

                time_frame = makeTimeFrameObjWithMonth(month=selected_month.number, hourly=selected_hours.value)

                weather_data = query_infrared_epw(
                        file_name=weather_file,
                        type=Query_Type.UTCI,
                        time_frame=time_frame,
                        api_key=self.api_key
                    )
                center_lon, center_lat = get_center_lon_lat_from_bbox(self.bbox,self.crs)

                payload = get_solar_radiation_payload(weather_data,center_lon, center_lat, time_frame)

            elif self.analysis_type == AnalysisType.DAYLIGHT_AVAILABILITY:
                try:
                    selected_month = self.month_dropdown_da.currentData()
                    selected_hours = self.hours_dropdown_da.currentData()

                except AttributeError:
                    logger.warning("Missing input, Selected month and hours are required.")
                    QMessageBox.warning(self, "Missing Input", "Selected month and hours are required.")
                    return

                center_lon, center_lat = get_center_lon_lat_from_bbox(self.bbox, self.crs)
                payload = get_daylight_availability_payload(month=selected_month.number, hourly=selected_hours.value, lon=center_lon, lat=center_lat)

            elif self.analysis_type == AnalysisType.DIRECT_SUN_HOURS:
                try:
                    selected_month = self.month_dropdown_dsh.currentData()
                    selected_hours = self.hours_dropdown_dsh.currentData()

                except AttributeError:
                    logger.warning("Missing input, Selected month and hours are required.")
                    QMessageBox.warning(self, "Missing Input", "Selected month and hours are required.")
                    return

                center_lon, center_lat = get_center_lon_lat_from_bbox(self.bbox, self.crs)
                payload = get_direct_sun_hours_payload(month=selected_month.number, hourly=selected_hours.value, lon=center_lon, lat=center_lat)

            elif self.analysis_type == AnalysisType.SKY_VIEW_FACTORS:

                payload = { "analysis-type": self.analysis_type.value, "geometries": None}

            logger.info(f"\n✨ ✨ ✨ ✨\nPayload: \n{payload}\n✨ ✨ ✨ ✨")
            #Load dotbim
            dotbim = load_dotbim(self.dotbim_path)
            if dotbim is not None:
                payload["geometries"] = dotbim
            else:
                logger.warning("Geometries data is empty")
                deselect_all()
                QMessageBox.warning(self, "Missing Geometry", "Please select geometry on the buildings layer.")
                return

            if tree_dotbim is not None:
                payload["vegetation"] = tree_dotbim
                logger.warning("Vegetation data was loaded.")
            else:
                logger.warning("Vegetation data is empty")

            # Run simulation
            self.geotiff_path, api_min_legend, api_max_legend = process_run_analysis(
                payload=payload,
                geometry_path=self.dotbim_path,
                bbox=self.bbox,
                crs=self.crs,
                api_key=self.api_key,
                analysis_type=self.analysis_type.value,
                do_crop=False,
                criteria=criteria
            )

            if not self.geotiff_path:
                logger.error("Simulation failed to produce a geotiff path.")
                QMessageBox.warning(self, "Simulation Failed", "Simulation failed to produce a result.")
                return

            # Determine legend min/max to use for display
            if self.analysis_type == AnalysisType.THERMAL_COMFORT_INDEX:
                # User checkbox overrides API value; fall back to API if not checked
                min_legend_value = self.selected_legend_min if self.legend_min_enable_tci.isChecked() else api_min_legend
                max_legend_value = self.selected_legend_max if self.legend_max_enable_tci.isChecked() else api_max_legend
                logger.info(f"TCI legend: min={min_legend_value}, max={max_legend_value} (user override: min={self.legend_min_enable_tci.isChecked()}, max={self.legend_max_enable_tci.isChecked()})")
            elif self.analysis_type in {
                AnalysisType.SOLAR_RADIATION,
                AnalysisType.DAYLIGHT_AVAILABILITY,
                AnalysisType.DIRECT_SUN_HOURS,
                AnalysisType.SKY_VIEW_FACTORS,
            }:
                min_legend_value = api_min_legend
                max_legend_value = api_max_legend
                logger.info(f"Using API legend range: min={min_legend_value}, max={max_legend_value}")
            else:
                min_legend_value = None
                max_legend_value = None

            # Display results
            add_geojson_then_raster(
                geojson_path=self.geojson_path,
                geotiff_path=self.geotiff_path,
                analysis_type=self.analysis_type.value,
                sub_analysis_type=self.sub_analysis_type,
                raster_opacity=0.7,
                min_legend_value=min_legend_value,
                max_legend_value=max_legend_value)


            super().accept()

        except InfraredAPIError as e:
            logger.error("API error in accept(): %s", e, exc_info=True)
            QMessageBox.critical(self, e.title, e.detail)
        except Exception as e:
            logger.error("Unhandled exception in accept(): %s", e, exc_info=True)
            msg = str(e)
            short_msg = msg if len(msg) < 200 else msg[:200] + "…"
            QMessageBox.critical(
                self,
                "Error",
                "An error occurred during the simulation.\n"
                f"Details: {short_msg}\n\nCheck the plugin log for more information."
            )
