# -*- coding: utf-8 -*-
"""
/***************************************************************************
 InfraredCityDialog
                                 A QGIS plugin
 This is a plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-13
        git sha              : $Format:%H$
        copyright            : (C) 2025 by infrared.city
        email                : connectors@infrared.city
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from infrared_sdk import InfraredClient
from qgis.core import Qgis
from qgis.PyQt import QtWidgets, uic
from qgis.PyQt.QtWidgets import QMessageBox
from qgis.utils import iface

from .exceptions import InfraredAPIError
from .infrared_logger import logger
from .models.analysis import (
    AnalysisType,
    PedestrianWindComfortType,
    ThermalComfortStatisticsType,
)
from .models.timeframes_parser import (
    DailyTimeFrameConfig,
    DailyTimeFrameConfigUTCI,
    MonthConfig,
    SeasonalTimeFrameConfig,
)
from .services.fetch import fetch_weather_file_names
from .services.geometry import (
    create_wgs84_geojson_polygon_from_selection,
    get_center_lon_lat_from_bbox,
    get_selected_bbox,
    get_selected_crs,
)
from .services.qgis_area_buildings import collect_qgis_area_buildings
from .services.sdk_runner import run_sdk_area_async
from .services.secret_manager import get_api_key
from .services.tree_layer_picker import (
    populate_tree_layer_dropdown,
    update_tree_layer_enabled,
)

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'infrared_city_run_simulation_dialog.ui'))


class InfraredCityRunMultipleSimulationDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)

        self._init_ok = False

        self.dotbim_path = None
        self.geojson_path = None
        self.geotiff_path = None
        self.colors = None
        self.analysis_type_dropdown.clear()
        for t in AnalysisType:
            self.analysis_type_dropdown.addItem(str(t), t)
        self.analysis_type_dropdown.currentTextChanged.connect(self.on_analysis_changed)
        self.analysis_type = None
        self.min_legend_value = None
        self.max_legend_value = None
        self.api_key = None
        self.polygon = None
        self.tile_count = None
        self.weather_file_names = []
        try:
            w,s,e,n = get_selected_bbox()
            self.bbox =[w,s,e,n]
            self.crs = get_selected_crs()

            iface.messageBar().pushMessage(
                            "InfraredCity",
                            f"Layer CRS is the following: {self.crs}",
                            level=Qgis.Info,
                            duration=7
                        )

        except Exception as e:
            logger.error(f"Failed to get selected bbox: {e}")
            QMessageBox.warning(self, "Invalid selection", "Invalid selection please select geometry.")
            self.reject()
            return

        self.button_box.accepted.connect(self.accept)
        self.button_box.rejected.connect(self.reject)

        # Populate the "Tree layer" dropdown from the current project; the
        # subsequent on_analysis_changed call will grey it out if either
        # there are no candidate layers or the analysis doesn't support
        # vegetation.
        try:
            populate_tree_layer_dropdown(self.tree_layer_dropdown)
        except AttributeError:
            # Older .ui without the tree_layer_dropdown widget — fall back
            # silently rather than failing the whole dialog.
            logger.warning("tree_layer_dropdown not present in dialog — skipping")

        if self.analysis_type_dropdown.count() > 0:
            self.analysis_type_dropdown.setCurrentIndex(0)
            self.on_analysis_changed(self.analysis_type_dropdown.currentText())


        # Load API key from QSettings (or INFRARED_API_KEY env var) via the
        # secret_manager. The legacy settings/user.json file is no longer
        # consulted — the Save API Key dialog writes only to QSettings.
        try:
            self.api_key = get_api_key()
            if self.api_key:
                logger.info("API key loaded")
        except Exception as e:
            logger.warning("Could not read API key: %s", e)

        if not self.api_key:
            QMessageBox.warning(
                self,
                "Missing API Key",
                "No API key found. Please save your API key first via the 'Save API Key' menu."
            )
            self.reject()
            return

        try:

            client = InfraredClient(api_key=self.api_key)
            self.polygon = create_wgs84_geojson_polygon_from_selection()
            preview = client.preview_area(self.polygon)
            logger.info("Preview area: %s", preview.tile_count)
            self.tile_count = preview.tile_count

            if preview.tile_count > 100:
                QMessageBox.warning(
                    self,
                    "Wrong selection",
                    "The tile size can be between 0 and 100. Larger areas are not allowed. 2"
                )
                self.reject()
                return

        except Exception as e:
            logger.exception("Error computing/plotting selection polygon: %s", e)
            QMessageBox.warning(
                self,
                "Error",
                f"An error occurred while computing the selection polygon. Please try again. Message: {e}"
            )
            self.reject()
            return

        self.setWindowTitle(f"Run Multiple Simulations — {self.tile_count} tile{'s' if self.tile_count != 1 else ''} selected")
        logger.info("Dialog loaded, tile count: %d", self.tile_count)
        self._init_ok = True

    def on_analysis_changed(self, text):
        current = self.analysis_type_dropdown.currentData()

        # Refresh the tree-layer dropdown's enabled state — disabled when
        # the project has no tree-* layers OR when the new analysis type
        # is in the no-vegetation list (currently empty, all 8 supported).
        try:
            update_tree_layer_enabled(self.tree_layer_dropdown, current)
        except AttributeError:
            pass  # older .ui without the field

        if self.bbox is not None and self.api_key and not self.weather_file_names:
            lon, lat = get_center_lon_lat_from_bbox(self.bbox, self.crs)
            try:
                self.weather_file_names = fetch_weather_file_names(lon, lat, 100, self.api_key)
            except InfraredAPIError as e:
                logger.error("API error fetching weather file names: %s", e, exc_info=True)
                QMessageBox.critical(self, e.title, e.detail)
                return
            except Exception as e:
                logger.error("Unexpected error fetching weather file names: %s", e, exc_info=True)
                QMessageBox.critical(self, "Error", f"Failed to fetch weather file names.\n\n{e}")
                return

        # Switch stacked pages by widget name — robust against page reordering
        _page_map = {
            AnalysisType.WIND_SPEED: self.page_wind_speed,
            AnalysisType.PEDESTRIAN_WIND_COMFORT: self.page_pedestrian_wind_comfort,
            AnalysisType.THERMAL_COMFORT_INDEX: self.page_thermal_comfort_index,
            AnalysisType.THERMAL_COMFORT_STATISTICS: self.page_thermal_comfort_statistics,
            AnalysisType.SOLAR_RADIATION: self.page_solar_radiation,
            AnalysisType.DAYLIGHT_AVAILABILITY: self.page_daylight_availability,
            AnalysisType.DIRECT_SUN_HOURS: self.page_direct_sun_hours,
            AnalysisType.SKY_VIEW_FACTORS: self.page_sky_view_factors,
        }
        try:
            page = _page_map.get(current)
            if page is not None:
                self.content_stack.setCurrentWidget(page)
        except AttributeError:
            # Fallback for older UI without stacked widget
            try:
                self.group_wind_speed.setVisible(current == AnalysisType.WIND_SPEED)
                self.group_pedestrian_wind_comfort.setVisible(current == AnalysisType.PEDESTRIAN_WIND_COMFORT)
                self.group_thermal_comfort.setVisible(current == AnalysisType.THERMAL_COMFORT_INDEX)
                self.group_thermal_comfort_statistics.setVisible(current == AnalysisType.THERMAL_COMFORT_STATISTICS)
                self.group_solar_radiation.setVisible(current == AnalysisType.SOLAR_RADIATION)
                self.group_daylight_availability.setVisible(current == AnalysisType.DAYLIGHT_AVAILABILITY)
                self.group_direct_sun_hours.setVisible(current == AnalysisType.DIRECT_SUN_HOURS)
                self.group_sky_view_factors.setVisible(current == AnalysisType.SKY_VIEW_FACTORS)
                #self.group_shadow_mask.setVisible(current == AnalysisType.SHADOW_MASK)
            except AttributeError as e:
                logger.error("Failed to update group visibility: %s", str(e), exc_info=True)

        if current == AnalysisType.PEDESTRIAN_WIND_COMFORT:
            try:
                self.weather_file_input_pwc.setEditable(True)
                self.weather_file_input_pwc.clear()

                for w in self.weather_file_names:
                    self.weather_file_input_pwc.addItem(w, w)

                self.pwc_type_dropdown.clear()
                for s in PedestrianWindComfortType:
                    self.pwc_type_dropdown.addItem(str(s), s)

                self.season_dropdown_pwc.clear()
                for season in SeasonalTimeFrameConfig:
                    self.season_dropdown_pwc.addItem(season.value, season)

                self.hours_dropdown_pwc.clear()
                for hours in DailyTimeFrameConfig:
                    self.hours_dropdown_pwc.addItem(hours.value, hours)
            except Exception as e:
                logger.error("Failed to populate PWC dialog elements: %s", str(e), exc_info=True)
        if current == AnalysisType.THERMAL_COMFORT_INDEX:
            try:
                self.weather_file_input_tci.setEditable(True)
                self.weather_file_input_tci.clear()

                for w in self.weather_file_names:
                    self.weather_file_input_tci.addItem(w, w)

                self.legend_min_input_tci.setEnabled(False)
                self.legend_max_input_tci.setEnabled(False)
                self.legend_min_enable_tci.toggled.connect(self.legend_min_input_tci.setEnabled)
                self.legend_max_enable_tci.toggled.connect(self.legend_max_input_tci.setEnabled)

                self.month_dropdown_tci.clear()
                for month in MonthConfig:
                    self.month_dropdown_tci.addItem(month.value, month)

                self.hours_dropdown_tci.clear()
                for hours in DailyTimeFrameConfigUTCI:
                    self.hours_dropdown_tci.addItem(hours.value, hours)
            except AttributeError as e:
                logger.error("Failed to populate TCI dialog elements: %s", str(e), exc_info=True)
        if current == AnalysisType.THERMAL_COMFORT_STATISTICS:
            try:
                self.weather_file_input_tcs.setEditable(True)
                self.weather_file_input_tcs.clear()

                for w in self.weather_file_names:
                    self.weather_file_input_tcs.addItem(w, w)

                self.season_dropdown_tcs.clear()
                for season in SeasonalTimeFrameConfig:
                    self.season_dropdown_tcs.addItem(season.value, season)

                self.hours_dropdown_tcs.clear()
                for hours in DailyTimeFrameConfigUTCI:
                    self.hours_dropdown_tcs.addItem(hours.value, hours)

                self.tcs_type_dropdown.clear()
                for tcs_type in ThermalComfortStatisticsType:
                    self.tcs_type_dropdown.addItem(tcs_type.value, tcs_type)
            except Exception as e:
                logger.error("Failed to populate TCS dialog elements: %s", str(e), exc_info=True)
        if current == AnalysisType.SOLAR_RADIATION:
            try:
                self.weather_file_input_sr.setEditable(True)
                self.weather_file_input_sr.clear()

                for w in self.weather_file_names:
                    self.weather_file_input_sr.addItem(w, w)

                self.month_dropdown_sr.clear()
                for month in MonthConfig:
                    self.month_dropdown_sr.addItem(month.value, month)

                self.hours_dropdown_sr.clear()
                for hours in DailyTimeFrameConfig:
                    self.hours_dropdown_sr.addItem(hours.value, hours)
            except Exception as e:
                logger.error("Failed to populate solar radiation dialog elements: %s", str(e), exc_info=True)
        if current == AnalysisType.DAYLIGHT_AVAILABILITY:
            try:
                self.month_dropdown_da.clear()
                for month in MonthConfig:
                    self.month_dropdown_da.addItem(month.value, month)

                self.hours_dropdown_da.clear()
                for hours in DailyTimeFrameConfig:
                    self.hours_dropdown_da.addItem(hours.value, hours)
            except Exception as e:
                logger.error("Failed to populate daylight availability dialog elements: %s", str(e), exc_info=True)
        if current == AnalysisType.DIRECT_SUN_HOURS:
            try:
                self.month_dropdown_dsh.clear()
                for month in MonthConfig:
                    self.month_dropdown_dsh.addItem(month.value, month)

                self.hours_dropdown_dsh.clear()
                for hours in DailyTimeFrameConfig:
                    self.hours_dropdown_dsh.addItem(hours.value, hours)
            except Exception as e:
                logger.error("Failed to populate direct sun hours dialog elements: %s", str(e), exc_info=True)

    def accept(self):
        try:
            logger.info("\n ✨ ✨ ✨ ✨ ✨ ✨ ✨ MULTIPLE SIMULATION RUN START ✨ ✨ ✨ ✨ ✨ ✨ ✨ ")

            if not self.api_key:
                QMessageBox.warning(self, "Missing API Key",
                    "No API key found. Please save your API key first via the 'Save API Key' menu.")
                return

            if self.polygon is None:
                logger.warning("No valid selection — cannot fetch buildings")
                QMessageBox.warning(self, "No selection",
                    "Select one or more features before running the simulation.")
                return
            logger.info("Polygon (WGS84) ring length: %d", len(self.polygon["coordinates"][0]))

            # Collect buildings from the active QGIS layer instead of the
            # SDK's Mapbox fetch — same return type (AreaBuildings, in
            # polygon-bbox-SW frame), so it plugs straight into
            # run_area_and_wait(buildings=area.buildings) below.
            area = collect_qgis_area_buildings(self.polygon)
            logger.info("Total buildings (from QGIS): %s", area.total_buildings)

            # Async path: submit jobs, hand off to a QTimer-driven poller,
            # then close the dialog immediately. The poller is parented to
            # iface.mainWindow() so it survives this dialog being destroyed
            # and renders the result on the canvas when polling completes.
            poller = run_sdk_area_async(self, self.polygon, area)
            if poller is None:
                # Payload validation failed; build_sdk_payload already
                # showed a QMessageBox. Keep the dialog open.
                return
            super().accept()

        except InfraredAPIError as e:
            logger.error("API error in accept(): %s", e, exc_info=True)
            QMessageBox.critical(self, e.title, e.detail)
        except Exception as e:
            logger.error("Unhandled exception in accept(): %s", e, exc_info=True)
            msg = str(e)
            short_msg = msg if len(msg) < 200 else msg[:200] + "…"
            QMessageBox.critical(
                self,
                "Error",
                "An error occurred during the simulation.\n"
                f"Details: {short_msg}\n\nCheck the plugin log for more information."
            )
