# -*- coding: utf-8 -*-
"""
/***************************************************************************
 InfraredCityDialog
                                 A QGIS plugin
 This is a plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-13
        git sha              : $Format:%H$
        copyright            : (C) 2025 by infrared.city
        email                : daniel.lepold@infrared.city
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtWidgets import QMessageBox
from qgis.PyQt.QtCore import QSettings
from .infrared_logger import logger
from .models.vegetation_types import TreeType, TreeSize

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'infrared_city_tree_catalog_dialog.ui'))


class InfraredCityTreeCatalogDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(InfraredCityTreeCatalogDialog, self).__init__(parent)

        self.setupUi(self)
        logger.info("Dialog loaded")
        
        # Populate combo boxes with enum values
        try:
            self.combo_tree_type.clear()
            self.combo_tree_type.addItems([str(t) for t in TreeType])

            self.combo_tree_size.clear()
            self.combo_tree_size.addItems([str(s) for s in TreeSize])

            # Try to restore last saved selection from settings
            settings = QSettings()
            saved_type = settings.value("infrared_city/tree_type", None)
            saved_size = settings.value("infrared_city/tree_size", None)

            if saved_type:
                for idx, t in enumerate(TreeType):
                    if t.value == saved_type:
                        self.combo_tree_type.setCurrentIndex(idx)
                        break

            if saved_size:
                for idx, s in enumerate(TreeSize):
                    if s.value == saved_size:
                        self.combo_tree_size.setCurrentIndex(idx)
                        break
        except Exception as e:
            logger.error("Failed to populate tree catalog combos: %s", e, exc_info=True)
            QMessageBox.critical(self, "Error", str(e))

    def accept(self):
        """Store selected TreeType and TreeSize, then close dialog."""
        try:
            # Map current index back to enum values (order is the same as added above)
            type_index = self.combo_tree_type.currentIndex()
            size_index = self.combo_tree_size.currentIndex()

            tree_types = list(TreeType)
            tree_sizes = list(TreeSize)

            self.selected_tree_type = tree_types[type_index] if 0 <= type_index < len(tree_types) else None
            self.selected_tree_size = tree_sizes[size_index] if 0 <= size_index < len(tree_sizes) else None

            logger.info(
                "Tree catalog selection - type: %s, size: %s",
                self.selected_tree_type,
                self.selected_tree_size,
            )

            # Persist selection so other dialogs (run_simulation, run_multiple) can reuse it
            settings = QSettings()
            if self.selected_tree_type is not None:
                settings.setValue("infrared_city/tree_type", self.selected_tree_type.value)
            if self.selected_tree_size is not None:
                settings.setValue("infrared_city/tree_size", self.selected_tree_size.value)
            
            QMessageBox.information(self, "Success", f"Tree catalog selection saved successfully with type: {self.selected_tree_type} and size: {self.selected_tree_size}")
        except Exception as e:
            logger.error("Error while reading tree catalog selection: %s", e, exc_info=True)
            QMessageBox.critical(self, "Error", str(e))
            return

        super().accept()